"use client";
import { useQueries } from "@tanstack/react-query";
import { ProtectedShell } from "@/components/protected-shell";
import { useApi } from "@/providers/providers";
import type { Clinic, Professional, Specialty, Unit } from "@/lib/api/types";
export default function CatalogPage() { const api = useApi(); const results = useQueries({ queries: [{ queryKey: ["clinic"], queryFn: () => api.request<Clinic>("/api/clinics/current") }, { queryKey: ["units"], queryFn: () => api.request<Unit[]>("/api/units") }, { queryKey: ["specialties"], queryFn: () => api.request<Specialty[]>("/api/specialties") }, { queryKey: ["professionals"], queryFn: () => api.request<Professional[]>("/api/professionals") }] }); const [clinic, units, specialties, professionals] = results; return <ProtectedShell><h1 className="text-2xl font-bold">Catálogo operacional</h1><p className="mt-1 text-slate-600">Dados carregados da API atual.</p><section className="mt-6 grid gap-4 md:grid-cols-2"><Panel title="Clínica">{clinic.data ? <p>{clinic.data.tradeName} · {clinic.data.timeZone}</p> : <Status loading={clinic.isLoading} />}</Panel><Panel title="Unidades"><List values={units.data?.map(item => item.name)} loading={units.isLoading} /></Panel><Panel title="Especialidades"><List values={specialties.data?.map(item => item.name)} loading={specialties.isLoading} /></Panel><Panel title="Profissionais"><List values={professionals.data?.map(item => item.name)} loading={professionals.isLoading} /></Panel></section></ProtectedShell>; }
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded bg-white p-5 shadow"><h2 className="font-semibold">{title}</h2><div className="mt-3">{children}</div></section>; }
function List({ values, loading }: { values?: string[]; loading: boolean }) { return loading ? <Status loading /> : <ul className="space-y-1">{values?.length ? values.map(value => <li key={value}>{value}</li>) : <li className="text-slate-600">Nenhum registro.</li>}</ul>; }
function Status({ loading }: { loading: boolean }) { return <p className="text-slate-600">{loading ? "Carregando..." : "Não disponível."}</p>; }
