import Link from "next/link";
import type { Metadata } from "next";
import { ProductShowcase } from "@/components/landing/product-showcase";
import { BrandLockup } from "@/components/brand/brand-lockup";
import { publicBrand } from "@/lib/brand/public-brand";
import { HowItWorksSection } from "@/components/landing/how-it-works-section";
import { ReceptionRoutineSection } from "@/components/landing/reception-routine-section";
import { OperationalResultsSection } from "@/components/landing/operational-results-section";
import { FaqSection, FinalCtaSection, LandingFooter, SecuritySection } from "@/components/landing/closing-sections";

export const metadata: Metadata = { metadataBase: new URL(process.env.NEXT_PUBLIC_SITE_URL ?? publicBrand.appUrl), title: `${publicBrand.name} | ${publicBrand.tagline}`, description: "Automatize consultas, disponibilidade e atendimento pelo WhatsApp sem perder o controle da operação.", alternates: { canonical: "/" }, openGraph: { title: `${publicBrand.name} | ${publicBrand.tagline}`, description: "WhatsApp, agenda e gestão conectados para a operação da sua clínica.", type: "website", url: "/" }, twitter: { card: "summary", title: `${publicBrand.name} | ${publicBrand.tagline}`, description: "WhatsApp, agenda e gestão conectados para a operação da sua clínica." } };

export default function LandingPage() {
  return <main className="min-h-screen bg-slate-950 text-white"><LandingHeader /><section className="mx-auto grid max-w-content gap-12 px-5 pb-20 pt-16 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:px-8 lg:pt-24"><div><p className="mb-4 text-sm font-semibold uppercase tracking-[.2em] text-brand-300">IA Recepção · operação B2B para clínicas</p><h1 className="max-w-3xl text-4xl font-semibold tracking-tight sm:text-6xl">Transforme o WhatsApp da sua clínica em uma recepção inteligente.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">Automatize consultas, disponibilidade, agendamentos e atendimento pelo WhatsApp sem perder o controle da operação.</p><div className="mt-8 flex flex-wrap gap-3"><Link className="rounded-control bg-brand-500 px-5 py-3 font-semibold text-white hover:bg-brand-400 focus:outline-none focus:ring-2 focus:ring-brand-300" href="mailto:demo@clinicassistant.local?subject=Solicitar%20demonstração">Solicitar demonstração</Link><Link className="rounded-control border border-white/20 px-5 py-3 font-semibold text-white hover:bg-white/10 focus:outline-none focus:ring-2 focus:ring-brand-300" href="#demo">Ver como funciona</Link></div></div><WhatsAppDemo /></section><section className="bg-white text-slate-950" id="problema"><div className="mx-auto max-w-content px-5 py-20 lg:px-8"><SectionIntro eyebrow="A rotina da recepção" title="Sua equipe não deveria passar o dia respondendo as mesmas perguntas." text="Horários, profissionais, reagendamentos e confirmações fazem parte da rotina da recepção. A IA Recepção organiza essas solicitações pelo WhatsApp e mantém sua equipe no controle quando é preciso intervir." /><ReceptionRoutineSection /></div></section><section className="bg-slate-50 text-slate-950" id="como-funciona"><div className="mx-auto max-w-content px-5 py-20 lg:px-8"><SectionIntro eyebrow="Como funciona" title="Do WhatsApp à operação da clínica." text="O paciente conversa pelo WhatsApp. A IA Recepção conduz as etapas necessárias, consulta a operação da clínica e envolve sua equipe quando o atendimento humano é necessário." /><HowItWorksSection /></div></section><ProductShowcase /><section className="bg-white text-slate-950" id="beneficios"><div className="mx-auto max-w-content px-5 py-20 lg:px-8"><SectionIntro eyebrow="Resultado para a operação" title="Menos tarefas repetitivas. Mais tempo para cuidar dos pacientes." text="A IA Recepção conecta atendimento, agenda e equipe para organizar as solicitações do dia a dia sem tirar sua recepção do controle." /><OperationalResultsSection /></div></section><SecuritySection /><FaqSection /><FinalCtaSection /><LandingFooter /></main>;
}

function LandingHeader() { return <header className="sticky top-0 z-20 border-b border-white/10 bg-slate-950/95 backdrop-blur"><div className="mx-auto flex max-w-content items-center justify-between px-5 py-4 lg:px-8"><Link href="/"><BrandLockup compact /></Link><nav className="hidden items-center gap-5 text-sm text-slate-300 sm:flex" aria-label="Navegação pública"><Link href="#problema">Problema</Link><Link href="#como-funciona">Como funciona</Link><Link href="#showcase">Produto</Link><Link href="#faq">FAQ</Link><Link className="text-white" href="/login">Entrar</Link></nav><details className="relative sm:hidden"><summary className="cursor-pointer list-none rounded-control border border-white/20 px-3 py-2 text-sm" aria-label="Abrir menu">Menu</summary><nav className="absolute right-0 mt-2 grid min-w-44 gap-2 rounded-panel border border-white/10 bg-slate-900 p-3 text-sm text-white shadow-floating" aria-label="Menu público"><Link href="#problema">Problema</Link><Link href="#como-funciona">Como funciona</Link><Link href="#showcase">Produto</Link><Link href="#faq">FAQ</Link><Link href="/login">Entrar</Link></nav></details></div></header>; }
function SectionIntro({ eyebrow, title, text, light = false }: { eyebrow: string; title: string; text?: string; light?: boolean }) { return <div><p className={`text-sm font-semibold uppercase tracking-[.18em] ${light ? "text-brand-300" : "text-brand-600"}`}>{eyebrow}</p><h2 className={`mt-3 text-3xl font-semibold tracking-tight sm:text-4xl ${light ? "text-white" : "text-slate-950"}`}>{title}</h2>{text && <p className={`mt-4 max-w-2xl text-lg leading-8 ${light ? "text-slate-300" : "text-slate-600"}`}>{text}</p>}</div>; }
function WhatsAppDemo() { return <div className="rounded-panel border border-white/10 bg-slate-900 p-4 shadow-floating" id="demo"><div className="border-b border-white/10 pb-4 text-sm font-semibold">Demonstração visual · 10:30</div><div className="grid gap-3 py-5 text-sm"><div className="max-w-[85%] rounded-panel bg-white/10 p-4 text-slate-200"><span className="text-xs text-slate-400">Paciente</span><p className="mt-1">Tem cardiologista amanhã?</p></div><div className="ml-auto max-w-[85%] rounded-panel bg-brand-600 p-4"><span className="text-xs text-brand-100">IA Recepção</span><p className="mt-1">Encontrei horários. Qual você prefere?</p></div><div className="max-w-[45%] rounded-panel bg-white/10 p-4 text-slate-200">10:30</div><div className="ml-auto max-w-[85%] rounded-panel bg-brand-600 p-4">Posso confirmar?</div><div className="ml-auto max-w-[85%] rounded-panel border border-emerald-300/40 bg-emerald-400/15 p-4 text-emerald-100">Consulta confirmada ✓<span className="mt-1 block text-xs text-emerald-200">Agenda · 10:30 — Nova consulta</span></div></div></div>; }
