"use client";

import { useQueries, useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { LoadingRow, RequestFeedback } from "@/components/request-feedback";
import { ProtectedShell } from "@/components/protected-shell";
import { ProfessionalForm } from "@/features/catalog/catalog-forms";
import { catalogApi } from "@/lib/api/catalog";
import { can } from "@/lib/auth/permissions";
import type { Professional } from "@/lib/api/types";
import { useApi, useAuth } from "@/providers/providers";

export default function ProfessionalsPage() { const api = useApi(); const { user } = useAuth(); const professionals = useQuery({ queryKey: ["professionals"], queryFn: () => catalogApi.listProfessionals(api) }); const [units, specialties] = useQueries({ queries: [{ queryKey: ["units"], queryFn: () => catalogApi.listUnits(api) }, { queryKey: ["specialties"], queryFn: () => catalogApi.listSpecialties(api) }] }); const [editing, setEditing] = useState<Professional | null | undefined>(); const formReady = !!units.data && !!specialties.data; const allowed = can(user, "manageCatalog"); return <ProtectedShell><header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">Profissionais</h1><p className="mt-1 text-slate-600">Cadastros do tenant atual.</p></div>{allowed && <button className="rounded bg-blue-700 px-4 py-2 text-white disabled:opacity-50" disabled={!formReady} onClick={() => setEditing(null)}>Novo profissional</button>}</header>{editing !== undefined && formReady && allowed && <ProfessionalForm professional={editing ?? undefined} units={units.data} specialties={specialties.data} onComplete={() => setEditing(undefined)} onCancel={() => setEditing(undefined)} />}<div className="mt-6 overflow-x-auto rounded bg-white shadow"><table className="w-full text-left"><thead><tr className="border-b"><th className="p-3">Nome</th><th className="p-3">E-mail</th><th className="p-3">Registro</th><th className="p-3">Status</th>{allowed && <th className="p-3"><span className="sr-only">Ações</span></th>}</tr></thead><tbody>{professionals.isLoading && <LoadingRow columns={allowed ? 5 : 4} />}{professionals.data?.map(item => <tr className="border-b" key={item.id}><td className="p-3">{item.name}</td><td className="p-3">{item.email}</td><td className="p-3">{item.registrationNumber}</td><td className="p-3">{item.status}</td>{allowed && <td className="p-3"><button className="text-blue-700 underline" onClick={() => setEditing(item)}>Editar</button></td>}</tr>)}</tbody></table><RequestFeedback error={professionals.error} /></div></ProtectedShell>; }
