<Project Sdk="Microsoft.NET.Sdk.Worker">
  <ItemGroup>
    <ProjectReference Include="../ClinicAssistant.Application/ClinicAssistant.Application.csproj" />
    <ProjectReference Include="../ClinicAssistant.Infrastructure/ClinicAssistant.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
    <PackageReference Include="RabbitMQ.Client" />
  </ItemGroup>
</Project>
