export type WikiCategory = "Técnica" | "Negócio" | "Implantação" | "Governança";
export type WikiStatus = "Current" | "NeedsReview" | "Deprecated";

export type WikiDocument = {
  slug: string;
  title: string;
  category: WikiCategory;
  description: string;
  tags: readonly string[];
  updatedAt: string;
  sourcePath: string;
  status: WikiStatus;
  content: string;
  related: readonly string[];
};

/** Curated, reviewed index. Documents remain versioned in Git; this is not a file browser. */
export const wikiDocuments: readonly WikiDocument[] = [
  { slug: "visao-produto", title: "Visão do produto", category: "Negócio", description: "Posicionamento da IA Recepção e o problema operacional que ela resolve.", tags: ["produto", "posicionamento", "SaaS"], updatedAt: "2026-08-25", sourcePath: "docs/product/value-proposition.md", status: "Current", related: ["fluxo-comercial", "onboarding-clinica"], content: "# Visão do produto\n\nA IA Recepção organiza o atendimento da clínica do WhatsApp à agenda, mantendo a equipe no controle quando a conversa precisa de intervenção humana.\n\n## Promessa operacional\n\n- Reduzir tarefas repetitivas da recepção.\n- Conduzir disponibilidade, agendamento, reagendamento e cancelamento.\n- Preservar contexto, histórico e governança por clínica.\n\nA apresentação comercial é uma estimativa operacional; não representa garantia de economia ou retorno financeiro." },
  { slug: "arquitetura-geral", title: "Arquitetura geral", category: "Técnica", description: "Mapa dos módulos da solução e das responsabilidades de cada camada.", tags: ["arquitetura", "backend", "frontend"], updatedAt: "2026-08-25", sourcePath: "docs/architecture.md", status: "Current", related: ["multi-tenant", "whatsapp"], content: "# Arquitetura geral\n\nO monorepo separa `backend/` e `frontend/`. O backend .NET concentra API, domínio, aplicação, infraestrutura e workers; o frontend Next.js apresenta a operação.\n\n## Fluxo principal\n\n1. A API autentica e autoriza o usuário.\n2. A infraestrutura aplica o escopo de tenant no PostgreSQL.\n3. RabbitMQ transporta eventos para o worker.\n4. Redis apoia estado efêmero e coordenação.\n5. O worker processa mensagens e outbox com retry.\n\nSegredos permanecem em variáveis de ambiente e nunca são publicados na Wiki." },
  { slug: "multi-tenant", title: "Arquitetura multi-tenant", category: "Técnica", description: "Isolamento de dados e responsabilidades entre plataforma e clínicas.", tags: ["multi-tenant", "segurança", "tenant"], updatedAt: "2026-08-25", sourcePath: "docs/architecture/whatsapp-provider-abstraction.md", status: "Current", related: ["arquitetura-geral", "onboarding-clinica"], content: "# Multi-tenant\n\nCada clínica possui um tenant próprio. Usuários de clínica operam somente no tenant autorizado; o PlatformAdmin possui escopo global para provisionar e acompanhar operações.\n\n## Regras\n\n- Consultas de domínio devem respeitar o contexto do tenant.\n- Integrações WhatsApp são cadastradas por clínica.\n- Ações administrativas relevantes geram auditoria.\n- Dados globais não devem ser usados para inferir acesso clínico." },
  { slug: "whatsapp", title: "WhatsApp por clínica", category: "Técnica", description: "Configuração, validação e operação dos canais WhatsApp multi-tenant.", tags: ["WhatsApp", "Twilio", "webhook"], updatedAt: "2026-08-25", sourcePath: "docs/operations/platformadmin-whatsapp-sender-guide.md", status: "Current", related: ["onboarding-clinica", "troubleshooting"], content: "# WhatsApp por clínica\n\nO PlatformAdmin cadastra o sender em **Plataforma → clínica → WhatsApp**. Cada canal possui origem, uso atual, status de onboarding e validação operacional.\n\n## Checklist\n\n- Confirmar `whatsapp:+...` do sender.\n- Registrar webhook inbound e status callback no provedor.\n- Validar conexão no painel.\n- Enviar uma mensagem real controlada e conferir inbound, outbox e histórico.\n\nNunca cole Account SID, Auth Token ou connection strings na documentação." },
  { slug: "onboarding-clinica", title: "Onboarding de clínica", category: "Implantação", description: "Roteiro operacional para provisionar uma clínica até o go-live.", tags: ["onboarding", "implantação", "go-live"], updatedAt: "2026-08-25", sourcePath: "docs/platform/clinic-onboarding.md", status: "Current", related: ["whatsapp", "pricing"], content: "# Onboarding de clínica\n\n1. Criar a clínica e o tenant.\n2. Criar unidade e confirmar fuso horário.\n3. Criar o ClinicAdmin.\n4. Configurar especialidades e profissionais.\n5. Configurar horários, bloqueios e férias.\n6. Cadastrar o canal WhatsApp da clínica.\n7. Validar inbound e outbound.\n8. Executar smoke test e confirmar o checklist.\n9. Ativar a clínica e monitorar os primeiros atendimentos.\n\nA conversão de um lead em tenant nunca ocorre automaticamente." },
  { slug: "deploy", title: "Deploy e produção", category: "Técnica", description: "Princípios para publicar frontend, API, worker e serviços gerenciados.", tags: ["deploy", "Railway", "Vercel", "produção"], updatedAt: "2026-08-25", sourcePath: "docs/deployment/production-readiness-audit.md", status: "NeedsReview", related: ["seguranca", "troubleshooting"], content: "# Deploy e produção\n\nAntes do deploy, valide migrations, `Jwt:Secret`, PostgreSQL, Redis, RabbitMQ/CloudAMQP, CORS, domínio e health checks.\n\n## Operação segura\n\n- Aplicar migrations de forma incremental e observável.\n- Fazer backup antes de alterações de banco.\n- Conferir logs da API e worker separadamente.\n- Validar `/health/ready` após cada publicação.\n\nAs variáveis reais ficam no Railway/Vercel, não no repositório." },
  { slug: "seguranca", title: "Segurança e autorização", category: "Governança", description: "Controles de acesso, sessão, escopo de tenant e segredos.", tags: ["segurança", "autorização", "segredos"], updatedAt: "2026-08-25", sourcePath: "docs/security/authorization.md", status: "Current", related: ["multi-tenant", "deploy"], content: "# Segurança e autorização\n\nA área PlatformAdmin é restrita pela policy `PlatformAdmin`. ClinicAdmin, Receptionist e Professional não devem acessar documentação interna, monetização ou leads globais.\n\nSegredos devem ser injetados por ambiente, rotacionados quando necessário e mascarados nos logs. A auditoria registra alterações administrativas sem incluir credenciais." },
  { slug: "troubleshooting", title: "Troubleshooting operacional", category: "Governança", description: "Roteiro para investigar falhas sem recriar o banco ou perder dados.", tags: ["troubleshooting", "incidente", "migrations"], updatedAt: "2026-08-25", sourcePath: "docs/testing/troubleshooting.md", status: "Current", related: ["deploy", "whatsapp"], content: "# Troubleshooting\n\n1. Identifique o serviço e o horário no log.\n2. Verifique health checks e dependências.\n3. Confirme a migration aplicada no banco correto.\n4. Reproduza com uma requisição mínima e idempotency key nova.\n5. Corrija de forma incremental e valide build, testes e smoke.\n\nNão apague o banco produtivo para corrigir uma migration; use o runbook de migrations e backup." },
  { slug: "pricing", title: "Pricing e modelo comercial", category: "Negócio", description: "Oferta apresentada atualmente e separação entre preço, implantação e billing futuro.", tags: ["pricing", "monetização", "comercial"], updatedAt: "2026-08-25", sourcePath: "docs/product/pricing-strategy.md", status: "Current", related: ["visao-produto", "fluxo-comercial"], content: "# Pricing\n\nA oferta pública atual é o **Plano Clínica**, com mensalidade e implantação definidos na configuração comercial compartilhada do frontend.\n\nO sistema ainda não possui billing automático. MRR, margem e custos reais devem aparecer como **Não disponível** ou **Aguardando dados reais** quando não houver fonte confiável.\n\nNão confundir estimativa da calculadora de valor com cobrança ou promessa de retorno." },
  { slug: "fluxo-comercial", title: "Fluxo comercial e leads", category: "Negócio", description: "Como tratar solicitações de demonstração e avançar uma oportunidade.", tags: ["leads", "vendas", "demonstração"], updatedAt: "2026-08-25", sourcePath: "docs/product/demo-flow.md", status: "Current", related: ["pricing", "onboarding-clinica"], content: "# Fluxo comercial\n\nO formulário público cria um lead. O PlatformAdmin acompanha os status **Novo**, **Contatado**, **Qualificado**, **Demonstração agendada**, **Convertido** ou **Perdido**.\n\nRegistrar notas e próxima ação no detalhe do lead. Um lead convertido pode oferecer a criação de clínica, mas exige ação explícita do operador." },
  { slug: "go-live", title: "Checklist de go-live", category: "Implantação", description: "Últimas verificações antes de liberar uma clínica para uso.", tags: ["go-live", "smoke", "produção"], updatedAt: "2026-08-25", sourcePath: "docs/pilot/production-smoke-checklist.md", status: "Current", related: ["onboarding-clinica", "whatsapp"], content: "# Go-live\n\n- Clínica e unidade configuradas.\n- ClinicAdmin consegue entrar.\n- Especialidades, profissionais e horários revisados.\n- Sender WhatsApp validado e webhooks respondendo.\n- Mensagem inbound processada pelo worker.\n- Resposta outbound confirmada no provedor.\n- Fila humana e auditoria verificadas.\n- Contatos de suporte e plano de rollback registrados." },
];

export const wikiCategories: readonly WikiCategory[] = ["Técnica", "Negócio", "Implantação", "Governança"];

export function findWikiDocument(slug: string) { return wikiDocuments.find(document => document.slug === slug); }
