namespace ClinicAssistant.Contracts.Scheduling;

public sealed record PatientRequest(string Name, string Phone, string? Email, DateOnly? BirthDate, string ConsentStatus);
public sealed record AvailabilityRuleRequest(DayOfWeek DayOfWeek, TimeOnly StartTime, TimeOnly EndTime, int SlotDurationMinutes, bool Active);
public sealed record ScheduleBlockRequest(DateTimeOffset StartsAt, DateTimeOffset EndsAt, string? Reason);
public sealed record VacationRequest(DateTimeOffset StartsAt, DateTimeOffset EndsAt, string? Reason);
public sealed record AvailabilityRuleResponse(Guid Id, DayOfWeek DayOfWeek, TimeOnly StartTime, TimeOnly EndTime, int SlotDurationMinutes, bool Active);
public sealed record ScheduleBlockResponse(Guid Id, DateTimeOffset StartsAt, DateTimeOffset EndsAt, string? Reason);
public sealed record VacationResponse(Guid Id, DateTimeOffset StartsAt, DateTimeOffset EndsAt, string? Reason);
public sealed record ProfessionalScheduleResponse(IReadOnlyList<AppointmentListItem> Appointments, IReadOnlyList<ScheduleBlockResponse> Blocks, IReadOnlyList<VacationResponse> Vacations);
public sealed record AppointmentRequest(Guid ClinicUnitId, Guid ProfessionalId, Guid SpecialtyId, Guid PatientId, DateTimeOffset StartsAt, DateTimeOffset EndsAt, string Source, string? Notes);
public sealed record AppointmentOperationRequest(int ExpectedVersion);
public sealed record CancelAppointmentRequest(string Reason, int ExpectedVersion);
public sealed record RescheduleAppointmentRequest(DateTimeOffset StartsAt, DateTimeOffset EndsAt, int ExpectedVersion, string? Notes);
public sealed record PatientResponse(Guid Id, string Name, string Phone, string? Email, DateOnly? BirthDate, string ConsentStatus);
public sealed record PatientSearchRequest(int Page = 1, int PageSize = 25, string? Search = null, string? ConsentStatus = null);
public sealed record PatientListItem(Guid Id, string Name, string Phone, string? Email, DateOnly? BirthDate, string ConsentStatus, string Source, DateTimeOffset? LastContactAt);
public sealed record PatientPage(IReadOnlyList<PatientListItem> Items, int Page, int PageSize, int TotalCount);
public sealed record PatientAppointmentSummary(Guid Id, DateTimeOffset StartsAt, DateTimeOffset EndsAt, string Status, string Source);
public sealed record PatientConversationSummary(Guid Id, string Status, string AutomationMode, DateTimeOffset? LastMessageAt);
public sealed record PatientAuditSummary(DateTimeOffset OccurredAt, string Action, string Result);
public sealed record PatientDetailResponse(PatientResponse Patient, string Source, DateTimeOffset? FirstContactAt, DateTimeOffset? LastContactAt, IReadOnlyList<PatientAppointmentSummary> UpcomingAppointments, IReadOnlyList<PatientConversationSummary> Conversations, IReadOnlyList<PatientAuditSummary> RecentAudit);
public sealed record AppointmentResponse(Guid Id, Guid PatientId, Guid ProfessionalId, DateTimeOffset StartsAt, DateTimeOffset EndsAt, string Status);
public sealed record RescheduleAppointmentResponse(AppointmentResponse Original, AppointmentResponse Replacement, bool Replayed);
public sealed record AppointmentListItem(Guid Id, Guid ClinicUnitId, Guid ProfessionalId, Guid SpecialtyId, Guid PatientId, DateTimeOffset StartsAt, DateTimeOffset EndsAt, string Status, string Source, string? Notes);
public sealed record AppointmentSearchRequest(int Page = 1, int PageSize = 25, Guid? ProfessionalId = null, Guid? SpecialtyId = null, Guid? UnitId = null, Guid? PatientId = null, string? Status = null, string? Source = null, DateTimeOffset? From = null, DateTimeOffset? To = null, string? Sort = null);
public sealed record AppointmentPage(IReadOnlyList<AppointmentListItem> Items, int Page, int PageSize, int TotalCount);
public sealed record AppointmentDetailResponse(AppointmentListItem Appointment, string PatientName, string ProfessionalName, string UnitName, string SpecialtyName, DateTimeOffset? CancelledAt, string? CancellationReason, int Version);
public sealed record AvailableSlot(DateTimeOffset StartsAt, DateTimeOffset EndsAt);
