using ClinicAssistant.Application.Clinics;
using ClinicAssistant.Application.Identity;
using ClinicAssistant.Application.Realtime;
using ClinicAssistant.Contracts.Clinics;
using ClinicAssistant.Domain.Clinics;
using ClinicAssistant.Domain.Operations;
using ClinicAssistant.Infrastructure.Persistence;
using FluentValidation;
using Microsoft.EntityFrameworkCore;

namespace ClinicAssistant.Infrastructure.Clinics;

public sealed class ClinicCatalogService(ClinicAssistantDbContext db, TenantAccessGuard tenantGuard, IOperationalEventPublisher events) : IClinicCatalogService
{
    public async Task<ClinicResponse?> GetClinicAsync(CancellationToken ct) => (await db.Clinics.SingleOrDefaultAsync(ct)) is { } clinic ? Map(clinic) : null;
    public async Task<ClinicResponse> UpdateClinicAsync(ClinicRequest request, CancellationToken ct)
    {
        await new ClinicRequestValidator().ValidateAndThrowAsync(request, ct); var tenantId = tenantGuard.RequireTenantId();
        var clinic = await db.Clinics.SingleOrDefaultAsync(ct);
        var action = clinic is null ? "clinic.created" : "clinic.updated";
        if (clinic is null)
        {
            clinic = new Clinic(tenantId, request.LegalName, request.TradeName, request.Document, request.Email, request.Phone, request.TimeZone, request.AssistantDisplayName);
            db.Clinics.Add(clinic);
        }
        else clinic.Update(request.LegalName, request.TradeName, request.Document, request.Email, request.Phone, request.TimeZone, request.AssistantDisplayName);
        db.AuditRecords.Add(new AuditRecord(tenantId, null, action, "Clinic", clinic.Id, "Succeeded", "Clinic updated by clinic administration."));
        await db.SaveChangesAsync(ct); await PublishAuditAsync(tenantId, action, "Clinic", clinic.Id, ct); return Map(clinic);
    }
    public async Task<IReadOnlyList<UnitResponse>> GetUnitsAsync(CancellationToken ct) => await db.ClinicUnits.OrderBy(x => x.Name).Select(x => Map(x)).ToListAsync(ct);
    public async Task<UnitResponse?> GetUnitAsync(Guid id, CancellationToken ct) => (await db.ClinicUnits.FindAsync([id], ct)) is { } unit ? Map(unit) : null;
    public async Task<UnitDetailResponse?> GetUnitDetailAsync(Guid id, CancellationToken ct)
    {
        var unit = await db.ClinicUnits.SingleOrDefaultAsync(x => x.Id == id, ct); if (unit is null) return null;
        var timeZone = await db.Clinics.Where(x => x.Id == unit.ClinicId).Select(x => x.TimeZone).SingleAsync(ct);
        var hours = await db.UnitBusinessHours.Where(x => x.ClinicUnitId == id).OrderBy(x => x.DayOfWeek).Select(x => new UnitBusinessHourResponse(x.DayOfWeek, x.OpensAt, x.ClosesAt)).ToListAsync(ct);
        var professionals = await db.Professionals.Where(x => x.ClinicUnitId == id).OrderBy(x => x.Name).Select(x => new UnitProfessionalSummary(x.Id, x.Name, x.RegistrationNumber, x.Status.ToString())).ToListAsync(ct);
        var tenantId = tenantGuard.RequireTenantId(); var audit = await db.AuditRecords.AsNoTracking().Where(x => x.TenantId == tenantId && x.ResourceType == "ClinicUnit" && x.ResourceId == id).OrderByDescending(x => x.CreatedAt).Take(20).Select(x => new UnitAuditSummary(x.CreatedAt, x.Action, x.Result)).ToListAsync(ct);
        return new(Map(unit), timeZone, hours, professionals, audit);
    }
    public async Task<UnitResponse> CreateUnitAsync(UnitRequest request, CancellationToken ct)
    {
        await new UnitRequestValidator().ValidateAndThrowAsync(request, ct); var tenantId = tenantGuard.RequireTenantId(); var clinic = await db.Clinics.SingleOrDefaultAsync(ct) ?? throw new InvalidOperationException("Configure the clinic before adding units.");
        var unit = new ClinicUnit(tenantId, clinic.Id, request.Name, request.Address, request.Phone); db.ClinicUnits.Add(unit); db.AuditRecords.Add(new AuditRecord(tenantId, null, "unit.created", "ClinicUnit", unit.Id, "Succeeded", "Unit created by clinic administration.")); await db.SaveChangesAsync(ct); await PublishAuditAsync(tenantId, "unit.created", "ClinicUnit", unit.Id, ct); return Map(unit);
    }
    public async Task<UnitResponse> UpdateUnitAsync(Guid id, UnitRequest request, CancellationToken ct) { await new UnitRequestValidator().ValidateAndThrowAsync(request, ct); var tenantId = tenantGuard.RequireTenantId(); var unit = await Require(db.ClinicUnits, id, ct); unit.Update(request.Name, request.Address, request.Phone); db.AuditRecords.Add(new AuditRecord(tenantId, null, "unit.updated", "ClinicUnit", id, "Succeeded", "Unit updated by clinic administration.")); await db.SaveChangesAsync(ct); await PublishAuditAsync(tenantId, "unit.updated", "ClinicUnit", id, ct); return Map(unit); }
    public async Task DeleteUnitAsync(Guid id, CancellationToken ct) { var tenantId = tenantGuard.RequireTenantId(); var unit = await Require(db.ClinicUnits, id, ct); if (await db.Professionals.AnyAsync(x => x.ClinicUnitId == id, ct)) throw new InvalidOperationException("A unit with linked professionals cannot be deleted."); db.ClinicUnits.Remove(unit); db.AuditRecords.Add(new AuditRecord(tenantId, null, "unit.deleted", "ClinicUnit", id, "Succeeded", "Unit deleted by clinic administration.")); await db.SaveChangesAsync(ct); await PublishAuditAsync(tenantId, "unit.deleted", "ClinicUnit", id, ct); }
    public async Task SetUnitStatusAsync(Guid id, string status, CancellationToken ct) { var tenantId = tenantGuard.RequireTenantId(); var unit = await Require(db.ClinicUnits, id, ct); if (!Enum.TryParse<CatalogStatus>(status, true, out var value)) throw new InvalidOperationException("Invalid unit status."); unit.SetStatus(value); db.AuditRecords.Add(new AuditRecord(tenantId, null, "unit.status_changed", "ClinicUnit", id, "Succeeded", $"Unit status set to {value}.")); await db.SaveChangesAsync(ct); await PublishAuditAsync(tenantId, "unit.status_changed", "ClinicUnit", id, ct); }
    public async Task<IReadOnlyList<UnitBusinessHourResponse>> ReplaceUnitBusinessHoursAsync(Guid id, IReadOnlyList<UnitBusinessHourRequest> request, CancellationToken ct) { var tenantId = tenantGuard.RequireTenantId(); var unit = await Require(db.ClinicUnits, id, ct); if (request.GroupBy(x => x.DayOfWeek).Any(x => x.Count() > 1) || request.Any(x => x.ClosesAt <= x.OpensAt)) throw new InvalidOperationException("Business hours are invalid."); var current = await db.UnitBusinessHours.Where(x => x.ClinicUnitId == id).ToListAsync(ct); db.UnitBusinessHours.RemoveRange(current); var hours = request.Select(x => new UnitBusinessHour(tenantId, unit.Id, x.DayOfWeek, x.OpensAt, x.ClosesAt)).ToList(); db.UnitBusinessHours.AddRange(hours); db.AuditRecords.Add(new AuditRecord(tenantId, null, "unit.business_hours_updated", "ClinicUnit", id, "Succeeded", "Business hours updated.")); await db.SaveChangesAsync(ct); await PublishAuditAsync(tenantId, "unit.business_hours_updated", "ClinicUnit", id, ct); return hours.OrderBy(x => x.DayOfWeek).Select(x => new UnitBusinessHourResponse(x.DayOfWeek, x.OpensAt, x.ClosesAt)).ToList(); }
    public async Task<IReadOnlyList<SpecialtyResponse>> GetSpecialtiesAsync(CancellationToken ct) => await db.Specialties.OrderBy(x => x.Name).Select(x => Map(x)).ToListAsync(ct);
    public async Task<SpecialtyResponse> CreateSpecialtyAsync(SpecialtyRequest request, CancellationToken ct) { await new SpecialtyRequestValidator().ValidateAndThrowAsync(request, ct); var tenantId = tenantGuard.RequireTenantId(); var entity = new Specialty(tenantId, request.Name, request.Description); db.Specialties.Add(entity); db.AuditRecords.Add(new AuditRecord(tenantId, null, "specialty.created", "Specialty", entity.Id, "Succeeded", "Specialty created by clinic administration.")); await db.SaveChangesAsync(ct); await PublishAuditAsync(tenantId, "specialty.created", "Specialty", entity.Id, ct); return Map(entity); }
    public async Task<SpecialtyResponse> UpdateSpecialtyAsync(Guid id, SpecialtyRequest request, CancellationToken ct) { await new SpecialtyRequestValidator().ValidateAndThrowAsync(request, ct); var tenantId = tenantGuard.RequireTenantId(); var entity = await Require(db.Specialties, id, ct); entity.Update(request.Name, request.Description); db.AuditRecords.Add(new AuditRecord(tenantId, null, "specialty.updated", "Specialty", id, "Succeeded", "Specialty updated by clinic administration.")); await db.SaveChangesAsync(ct); await PublishAuditAsync(tenantId, "specialty.updated", "Specialty", id, ct); return Map(entity); }
    public async Task<SpecialtyDependenciesResponse> GetSpecialtyDependenciesAsync(Guid id, CancellationToken ct) { await Require(db.Specialties, id, ct); var professionals = await db.ProfessionalSpecialties.CountAsync(x => x.SpecialtyId == id, ct); var futureAppointments = await db.Appointments.CountAsync(x => x.SpecialtyId == id && x.StartsAt >= DateTimeOffset.UtcNow && x.Status != ClinicAssistant.Domain.Scheduling.AppointmentStatus.Cancelled, ct); return new(professionals == 0 && futureAppointments == 0, professionals, futureAppointments); }
    public async Task SetSpecialtyStatusAsync(Guid id, string status, CancellationToken ct) { var tenantId = tenantGuard.RequireTenantId(); var entity = await Require(db.Specialties, id, ct); if (!Enum.TryParse<CatalogStatus>(status, true, out var value)) throw new InvalidOperationException("Invalid specialty status."); if (value == CatalogStatus.Inactive && !(await GetSpecialtyDependenciesAsync(id, ct)).CanDeactivate) throw new InvalidOperationException("The specialty has active dependencies and cannot be deactivated."); entity.SetStatus(value); db.AuditRecords.Add(new AuditRecord(tenantId, null, "specialty.status_changed", "Specialty", id, "Succeeded", $"Specialty status set to {value}.")); await db.SaveChangesAsync(ct); await PublishAuditAsync(tenantId, "specialty.status_changed", "Specialty", id, ct); }
    public async Task DeleteSpecialtyAsync(Guid id, CancellationToken ct) { var tenantId = tenantGuard.RequireTenantId(); var entity = await Require(db.Specialties, id, ct); if (!(await GetSpecialtyDependenciesAsync(id, ct)).CanDeactivate) throw new InvalidOperationException("The specialty has dependencies and cannot be deleted."); db.Specialties.Remove(entity); db.AuditRecords.Add(new AuditRecord(tenantId, null, "specialty.deleted", "Specialty", id, "Succeeded", "Specialty deleted with no dependencies.")); await db.SaveChangesAsync(ct); await PublishAuditAsync(tenantId, "specialty.deleted", "Specialty", id, ct); }
    public async Task<IReadOnlyList<ProfessionalResponse>> GetProfessionalsAsync(CancellationToken ct) => (await db.Professionals.Include(x => x.Specialties).OrderBy(x => x.Name).ToListAsync(ct)).Select(Map).ToList();
    public async Task<ProfessionalResponse?> GetProfessionalAsync(Guid id, CancellationToken ct) => (await db.Professionals.Include(x => x.Specialties).SingleOrDefaultAsync(x => x.Id == id, ct)) is { } p ? Map(p) : null;
    public async Task<ProfessionalResponse> CreateProfessionalAsync(ProfessionalRequest request, CancellationToken ct) { await new ProfessionalRequestValidator().ValidateAndThrowAsync(request, ct); var tenantId = tenantGuard.RequireTenantId(); var p = await BuildProfessional(request, null, ct); db.Professionals.Add(p); db.AuditRecords.Add(new AuditRecord(tenantId, null, "professional.created", "Professional", p.Id, "Succeeded", "Professional created by clinic administration.")); await db.SaveChangesAsync(ct); await PublishAuditAsync(tenantId, "professional.created", "Professional", p.Id, ct); return Map(p); }
    public async Task<ProfessionalResponse> UpdateProfessionalAsync(Guid id, ProfessionalRequest request, CancellationToken ct) { await new ProfessionalRequestValidator().ValidateAndThrowAsync(request, ct); var tenantId = tenantGuard.RequireTenantId(); if (!await db.ClinicUnits.AnyAsync(x => x.Id == request.ClinicUnitId, ct)) throw new InvalidOperationException("Clinic unit not found."); var p = await Require(db.Professionals.Include(x => x.Specialties), id, ct); p.Update(request.ClinicUnitId, request.Name, request.Email, request.Phone, request.RegistrationNumber); p.Specialties.Clear(); await SetSpecialties(p, request.SpecialtyIds, ct); db.AuditRecords.Add(new AuditRecord(tenantId, null, "professional.updated", "Professional", id, "Succeeded", "Professional updated by clinic administration.")); await db.SaveChangesAsync(ct); await PublishAuditAsync(tenantId, "professional.updated", "Professional", id, ct); return Map(p); }
    public async Task DeleteProfessionalAsync(Guid id, CancellationToken ct) { var tenantId = tenantGuard.RequireTenantId(); db.Professionals.Remove(await Require(db.Professionals, id, ct)); db.AuditRecords.Add(new AuditRecord(tenantId, null, "professional.deleted", "Professional", id, "Succeeded", "Professional deleted by clinic administration.")); await db.SaveChangesAsync(ct); await PublishAuditAsync(tenantId, "professional.deleted", "Professional", id, ct); }
    private async Task<Professional> BuildProfessional(ProfessionalRequest r, Professional? ignored, CancellationToken ct) { var tenant = tenantGuard.RequireTenantId(); if (!await db.ClinicUnits.AnyAsync(x => x.Id == r.ClinicUnitId, ct)) throw new InvalidOperationException("Clinic unit not found."); var p = new Professional(tenant, r.ClinicUnitId, r.Name, r.Email, r.Phone, r.RegistrationNumber); await SetSpecialties(p, r.SpecialtyIds, ct); return p; }
    private async Task SetSpecialties(Professional p, IReadOnlyCollection<Guid> ids, CancellationToken ct) { var unique = ids.Distinct().ToArray(); if (unique.Length != ids.Count || await db.Specialties.CountAsync(x => unique.Contains(x.Id), ct) != unique.Length) throw new InvalidOperationException("One or more specialties are invalid for this tenant."); foreach (var id in unique) p.Specialties.Add(new ProfessionalSpecialty(p.Id, id)); }
    private static async Task<T> Require<T>(IQueryable<T> query, Guid id, CancellationToken ct) where T : class => await query.SingleOrDefaultAsync(x => EF.Property<Guid>(x, "Id") == id, ct) ?? throw new KeyNotFoundException("Resource not found.");
    private Task PublishAuditAsync(Guid tenantId, string action, string resourceType, Guid resourceId, CancellationToken ct) => events.PublishAsync(tenantId, "audit.created", new { Action = action, ResourceType = resourceType, ResourceId = resourceId, Result = "Succeeded" }, ct);
    private static ClinicResponse Map(Clinic x) => new(x.Id, x.LegalName, x.TradeName, x.Document, x.Email, x.Phone, x.TimeZone, x.Status.ToString(), x.AssistantDisplayName);
    private static UnitResponse Map(ClinicUnit x) => new(x.Id, x.ClinicId, x.Name, x.Address, x.Phone, x.Status.ToString());
    private static SpecialtyResponse Map(Specialty x) => new(x.Id, x.Name, x.Description, x.Status.ToString());
    private static ProfessionalResponse Map(Professional x) => new(x.Id, x.ClinicUnitId, x.Name, x.Email, x.Phone, x.RegistrationNumber, x.Status.ToString(), x.Specialties.Select(s => s.SpecialtyId).ToList());
}

file sealed class ClinicRequestValidator : AbstractValidator<ClinicRequest> { public ClinicRequestValidator() { RuleFor(x => x.LegalName).NotEmpty().MaximumLength(200); RuleFor(x => x.TradeName).NotEmpty().MaximumLength(200); RuleFor(x => x.Document).NotEmpty().MaximumLength(32); RuleFor(x => x.Email).EmailAddress().MaximumLength(320); RuleFor(x => x.Phone).NotEmpty().MaximumLength(32); RuleFor(x => x.TimeZone).NotEmpty().MaximumLength(100); RuleFor(x => x.AssistantDisplayName).MaximumLength(60).Must(value => string.IsNullOrWhiteSpace(value) || !value.Contains('<') && !value.Contains('>')).WithMessage("O nome da assistente contém caracteres inválidos."); } }
file sealed class UnitRequestValidator : AbstractValidator<UnitRequest> { public UnitRequestValidator() { RuleFor(x => x.Name).NotEmpty().MaximumLength(200); RuleFor(x => x.Address).NotEmpty().MaximumLength(500); RuleFor(x => x.Phone).NotEmpty().MaximumLength(32); } }
file sealed class SpecialtyRequestValidator : AbstractValidator<SpecialtyRequest> { public SpecialtyRequestValidator() { RuleFor(x => x.Name).NotEmpty().MaximumLength(160); RuleFor(x => x.Description).MaximumLength(1000); } }
file sealed class ProfessionalRequestValidator : AbstractValidator<ProfessionalRequest> { public ProfessionalRequestValidator() { RuleFor(x => x.ClinicUnitId).NotEmpty(); RuleFor(x => x.Name).NotEmpty().MaximumLength(200); RuleFor(x => x.Email).EmailAddress().MaximumLength(320); RuleFor(x => x.Phone).NotEmpty().MaximumLength(32); RuleFor(x => x.RegistrationNumber).NotEmpty().MaximumLength(80); RuleFor(x => x.SpecialtyIds).NotEmpty(); } }
