"use client";

import { useMutation, useQueries, useQuery, useQueryClient } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import { ProtectedShell } from "@/components/protected-shell";
import { appointmentsApi } from "@/lib/api/appointments";
import { catalogApi } from "@/lib/api/catalog";
import { patientsApi } from "@/lib/api/patients";
import type { AppointmentDetail, AppointmentRequest } from "@/lib/api/types";
import { useApi } from "@/providers/providers";
import { Button } from "@/components/ui/button";
import { DataTable, TableCell, TableHeader } from "@/components/ui/data-table";
import { Drawer } from "@/components/ui/drawer";
import { FormField, FormSection, Input, Select } from "@/components/ui/form";
import { Icon } from "@/components/ui/icon";
import { PageContainer, PageHeader } from "@/components/ui/page";
import { Card, StatusBadge } from "@/components/ui/surfaces";
import { EmptyState, ErrorState, Skeleton } from "@/components/ui/states";

export default function AppointmentsPage() {
  const api = useApi(); const client = useQueryClient(); const today = new Date().toISOString().slice(0, 10);
  const [date, setDate] = useState(today); const [detail, setDetail] = useState<AppointmentDetail | null>(null); const [rescheduleAt, setRescheduleAt] = useState("");
  const [form, setForm] = useState({ clinicUnitId: "", professionalId: "", specialtyId: "", patientId: "", startsAt: "", endsAt: "", notes: "" });
  const period = useMemo(() => ({ startsAt: `${date}T00:00:00.000Z`, endsAt: `${date}T23:59:59.999Z` }), [date]);
  const appointments = useQuery({ queryKey: ["appointments", period], queryFn: () => appointmentsApi.search(api, { page: 1, pageSize: 100, from: period.startsAt, to: period.endsAt }) });
  const [units, specialties, professionals, patients] = useQueries({ queries: [{ queryKey: ["units"], queryFn: () => catalogApi.listUnits(api) }, { queryKey: ["specialties"], queryFn: () => catalogApi.listSpecialties(api) }, { queryKey: ["professionals"], queryFn: () => catalogApi.listProfessionals(api) }, { queryKey: ["patients"], queryFn: () => patientsApi.list(api) }] });
  const slots = useQuery({ enabled: Boolean(form.professionalId), queryKey: ["availability", form.professionalId, date], queryFn: () => appointmentsApi.availability(api, form.professionalId, date) });
  const refresh = () => client.invalidateQueries({ queryKey: ["appointments"] });
  const create = useMutation({ mutationFn: (request: AppointmentRequest) => appointmentsApi.create(api, request, crypto.randomUUID()), onSuccess: async () => { await refresh(); setForm(value => ({ ...value, startsAt: "", endsAt: "", notes: "" })); } });
  const confirm = useMutation({ mutationFn: (item: AppointmentDetail) => appointmentsApi.confirm(api, item.appointment.id, item.version, crypto.randomUUID()), onSuccess: refresh });
  const cancel = useMutation({ mutationFn: (item: AppointmentDetail) => appointmentsApi.cancel(api, item.appointment.id, "Cancelamento administrativo", item.version, crypto.randomUUID()), onSuccess: refresh });
  const reschedule = useMutation({ mutationFn: (item: AppointmentDetail) => { const start = new Date(rescheduleAt); return appointmentsApi.reschedule(api, item.appointment.id, { startsAt: start.toISOString(), endsAt: new Date(start.getTime() + (new Date(item.appointment.endsAt).getTime() - new Date(item.appointment.startsAt).getTime())).toISOString(), expectedVersion: item.version, notes: item.appointment.notes }, crypto.randomUUID()); }, onSuccess: async () => { await refresh(); setDetail(null); setRescheduleAt(""); } });
  const submit = (event: React.FormEvent) => { event.preventDefault(); if (form.startsAt && form.endsAt) create.mutate({ ...form, startsAt: form.startsAt, endsAt: form.endsAt, source: "Dashboard", notes: form.notes || null }); };

  return <ProtectedShell><PageContainer><PageHeader description="Crie, acompanhe e atualize consultas da clínica com disponibilidade em tempo real." pathname="/appointments" title="Agenda" />
    <Card className="mt-6"><form className="grid gap-6" onSubmit={submit} aria-label="Agendamento manual"><FormSection description="Selecione a data e os vínculos necessários para criar uma consulta." title="Nova consulta"><FormField htmlFor="appointment-date" label="Data"><Input id="appointment-date" onChange={event => setDate(event.target.value)} type="date" value={date} /></FormField><FormField htmlFor="appointment-unit" label="Unidade"><Select id="appointment-unit" onChange={event => setForm(value => ({ ...value, clinicUnitId: event.target.value }))} value={form.clinicUnitId}><option value="">Selecione</option>{units.data?.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></FormField><FormField htmlFor="appointment-specialty" label="Especialidade"><Select id="appointment-specialty" onChange={event => setForm(value => ({ ...value, specialtyId: event.target.value }))} value={form.specialtyId}><option value="">Selecione</option>{specialties.data?.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></FormField><FormField htmlFor="appointment-professional" label="Profissional"><Select id="appointment-professional" onChange={event => setForm(value => ({ ...value, professionalId: event.target.value, startsAt: "", endsAt: "" }))} value={form.professionalId}><option value="">Selecione</option>{professionals.data?.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></FormField><FormField htmlFor="appointment-patient" label="Paciente"><Select id="appointment-patient" onChange={event => setForm(value => ({ ...value, patientId: event.target.value }))} value={form.patientId}><option value="">Selecione</option>{patients.data?.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></FormField><FormField htmlFor="appointment-notes" label="Observação administrativa"><Input id="appointment-notes" onChange={event => setForm(value => ({ ...value, notes: event.target.value }))} value={form.notes} /></FormField></FormSection>{slots.data && <section><h2 className="font-semibold text-slate-950">Horários disponíveis</h2><div className="mt-3 flex flex-wrap gap-2">{slots.data.map(slot => <Button key={slot.startsAt} onClick={() => setForm(value => ({ ...value, startsAt: slot.startsAt, endsAt: slot.endsAt }))} size="sm" type="button" variant={form.startsAt === slot.startsAt ? "primary" : "outline"}>{new Date(slot.startsAt).toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit" })}</Button>)}{slots.data.length === 0 && <p className="text-sm text-slate-600">Nenhum horário disponível.</p>}</div></section>}<div className="flex justify-end"><Button disabled={create.isPending || !form.clinicUnitId || !form.specialtyId || !form.professionalId || !form.patientId || !form.startsAt} loading={create.isPending} type="submit"><Icon name="calendar" />Criar consulta</Button></div></form></Card>
    <Drawer description="Consulte os dados vinculados e reagende quando necessário." onClose={() => setDetail(null)} open={Boolean(detail)} title="Detalhe do agendamento">{detail && <div className="grid gap-6">{reschedule.isError && <ErrorState description="Verifique a disponibilidade do novo horário." onRetry={() => reschedule.reset()} title="Não foi possível concluir a operação" />}<dl className="grid gap-4 text-sm sm:grid-cols-2">{[["Paciente", detail.patientName], ["Profissional", detail.professionalName], ["Unidade", detail.unitName], ["Especialidade", detail.specialtyName]].map(([label, value]) => <div key={label}><dt className="text-slate-500">{label}</dt><dd className="mt-1 font-medium">{value}</dd></div>)}</dl>{detail.appointment.status !== "Cancelled" && detail.appointment.status !== "Rescheduled" && <FormField htmlFor="reschedule-at" label="Novo horário"><Input id="reschedule-at" onChange={event => setRescheduleAt(event.target.value)} type="datetime-local" value={rescheduleAt} /><Button className="mt-3" disabled={!rescheduleAt} loading={reschedule.isPending} onClick={() => reschedule.mutate(detail)}>Reagendar</Button></FormField>}</div>}</Drawer>
  </PageContainer></ProtectedShell>;
}
