"use client";

import { useMutation, useQueries, useQuery, useQueryClient } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import { LoadingRow, RequestFeedback } from "@/components/request-feedback";
import { ProtectedShell } from "@/components/protected-shell";
import { appointmentsApi } from "@/lib/api/appointments";
import { catalogApi } from "@/lib/api/catalog";
import { patientsApi } from "@/lib/api/patients";
import type { AppointmentDetail, AppointmentRequest } from "@/lib/api/types";
import { useApi } from "@/providers/providers";

export default function AppointmentsPage() {
  const api = useApi(); const client = useQueryClient(); const today = new Date().toISOString().slice(0, 10); const [date, setDate] = useState(today); const [form, setForm] = useState({ clinicUnitId: "", professionalId: "", specialtyId: "", patientId: "", startsAt: "", endsAt: "", notes: "" });
  const period = useMemo(() => ({ startsAt: `${date}T00:00:00.000Z`, endsAt: `${date}T23:59:59.999Z` }), [date]);
  const appointments = useQuery({ queryKey: ["appointments", period], queryFn: () => appointmentsApi.search(api, { page: 1, pageSize: 100, from: period.startsAt, to: period.endsAt }) });
  const [detail, setDetail] = useState<AppointmentDetail | null>(null); const [rescheduleAt, setRescheduleAt] = useState("");
  const [units, specialties, professionals, patients] = useQueries({ queries: [{ queryKey: ["units"], queryFn: () => catalogApi.listUnits(api) }, { queryKey: ["specialties"], queryFn: () => catalogApi.listSpecialties(api) }, { queryKey: ["professionals"], queryFn: () => catalogApi.listProfessionals(api) }, { queryKey: ["patients"], queryFn: () => patientsApi.list(api) }] });
  const slots = useQuery({ enabled: !!form.professionalId, queryKey: ["availability", form.professionalId, date], queryFn: () => appointmentsApi.availability(api, form.professionalId, date) });
  const refresh = () => client.invalidateQueries({ queryKey: ["appointments"] });
  const create = useMutation({ mutationFn: (request: AppointmentRequest) => appointmentsApi.create(api, request, crypto.randomUUID()), onSuccess: async () => { await refresh(); setForm(value => ({ ...value, startsAt: "", endsAt: "", notes: "" })); } });
  const confirm = useMutation({ mutationFn: (item: AppointmentDetail) => appointmentsApi.confirm(api, item.appointment.id, item.version, crypto.randomUUID()), onSuccess: refresh });
  const cancel = useMutation({ mutationFn: (item: AppointmentDetail) => appointmentsApi.cancel(api, item.appointment.id, "Cancelamento administrativo", item.version, crypto.randomUUID()), onSuccess: refresh });
  const reschedule = useMutation({ mutationFn: (item: AppointmentDetail) => { const start = new Date(rescheduleAt); return appointmentsApi.reschedule(api, item.appointment.id, { startsAt: start.toISOString(), endsAt: new Date(start.getTime() + (new Date(item.appointment.endsAt).getTime() - new Date(item.appointment.startsAt).getTime())).toISOString(), expectedVersion: item.version, notes: item.appointment.notes }, crypto.randomUUID()); }, onSuccess: async () => { await refresh(); setDetail(null); setRescheduleAt(""); } });
  const requestCancellation = async (id: string) => { if (window.confirm("Cancelar esta consulta? Esta ação não pode ser desfeita.")) cancel.mutate(await appointmentsApi.detail(api, id)); };
  const submit = (event: React.FormEvent) => { event.preventDefault(); if (!form.startsAt || !form.endsAt) return; create.mutate({ ...form, startsAt: form.startsAt, endsAt: form.endsAt, source: "Dashboard", notes: form.notes || null }); };
  const chooseSlot = (startsAt: string, endsAt: string) => setForm(value => ({ ...value, startsAt, endsAt }));
  return <ProtectedShell><h1 className="text-2xl font-bold">Agenda</h1><p className="mt-1 text-slate-600">Consultas e disponibilidade da clínica atual.</p><label className="mt-5 block max-w-xs text-sm font-medium">Data<input className="mt-1 block w-full rounded border p-2" type="date" value={date} onChange={event => setDate(event.target.value)} /></label>
    <form className="mt-5 grid gap-3 rounded bg-white p-5 shadow md:grid-cols-3" onSubmit={submit} aria-label="Agendamento manual"><Select label="Unidade" value={form.clinicUnitId} values={units.data?.map(value => [value.id, value.name]) ?? []} onChange={value => setForm(current => ({ ...current, clinicUnitId: value }))} /><Select label="Especialidade" value={form.specialtyId} values={specialties.data?.map(value => [value.id, value.name]) ?? []} onChange={value => setForm(current => ({ ...current, specialtyId: value }))} /><Select label="Profissional" value={form.professionalId} values={professionals.data?.map(value => [value.id, value.name]) ?? []} onChange={value => setForm(current => ({ ...current, professionalId: value, startsAt: "", endsAt: "" }))} /><Select label="Paciente" value={form.patientId} values={patients.data?.map(value => [value.id, value.name]) ?? []} onChange={value => setForm(current => ({ ...current, patientId: value }))} /><label className="grid gap-1 text-sm font-medium">Observação administrativa<input className="rounded border p-2" value={form.notes} onChange={event => setForm(current => ({ ...current, notes: event.target.value }))} /></label><div className="flex items-end"><button className="rounded bg-blue-700 px-4 py-2 text-white disabled:opacity-50" disabled={create.isPending || !form.clinicUnitId || !form.specialtyId || !form.professionalId || !form.patientId || !form.startsAt}>Criar consulta</button></div>{slots.data && <div className="md:col-span-3"><p className="mb-2 text-sm font-medium">Horários disponíveis</p><div className="flex flex-wrap gap-2">{slots.data.map(slot => <button className={`rounded border px-3 py-1 ${form.startsAt === slot.startsAt ? "bg-blue-700 text-white" : "bg-white"}`} key={slot.startsAt} type="button" onClick={() => chooseSlot(slot.startsAt, slot.endsAt)}>{new Date(slot.startsAt).toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit" })}</button>)}{slots.data.length === 0 && <span className="text-sm text-slate-600">Nenhum horário disponível.</span>}</div></div>}<div className="md:col-span-3"><RequestFeedback error={create.error} /></div></form>
    <div className="mt-6 overflow-x-auto rounded bg-white shadow"><table className="w-full text-left"><thead><tr className="border-b"><th className="p-3">Horário</th><th className="p-3">Status</th><th className="p-3">Origem</th><th className="p-3">Ações</th></tr></thead><tbody>{appointments.isLoading && <LoadingRow columns={4} />}{appointments.data?.items.map(item => <tr className="border-b" key={item.id}><td className="p-3">{new Date(item.startsAt).toLocaleString("pt-BR")}</td><td className="p-3">{item.status}</td><td className="p-3">{item.source}</td><td className="p-3 space-x-3"><button className="text-blue-700 underline" onClick={async () => setDetail(await appointmentsApi.detail(api, item.id))}>Detalhe</button>{item.status === "Pending" && <button className="text-blue-700 underline" disabled={confirm.isPending} onClick={async () => confirm.mutate(await appointmentsApi.detail(api, item.id))}>Confirmar</button>}{item.status !== "Cancelled" && <button className="text-red-700 underline" disabled={cancel.isPending} onClick={() => requestCancellation(item.id)}>Cancelar</button>}</td></tr>)}</tbody></table><RequestFeedback error={appointments.error || confirm.error || cancel.error} /></div>{detail && <section className="mt-5 rounded bg-white p-4 shadow"><div className="flex justify-between"><h2 className="text-lg font-bold">Detalhe do agendamento</h2><button className="underline" onClick={() => setDetail(null)}>Fechar</button></div><dl className="mt-3 grid gap-2 text-sm md:grid-cols-2"><div><dt className="font-semibold">Paciente</dt><dd>{detail.patientName}</dd></div><div><dt className="font-semibold">Profissional</dt><dd>{detail.professionalName}</dd></div><div><dt className="font-semibold">Unidade</dt><dd>{detail.unitName}</dd></div><div><dt className="font-semibold">Especialidade</dt><dd>{detail.specialtyName}</dd></div></dl>{detail.cancellationReason && <p className="mt-3 text-sm">Motivo do cancelamento: {detail.cancellationReason}</p>}{detail.appointment.status !== "Cancelled" && detail.appointment.status !== "Rescheduled" && <div className="mt-4 flex flex-wrap items-end gap-3"><label className="grid gap-1 text-sm font-medium">Novo horário<input className="rounded border p-2" type="datetime-local" value={rescheduleAt} onChange={event => setRescheduleAt(event.target.value)} /></label><button className="rounded bg-blue-700 px-4 py-2 text-white disabled:opacity-50" disabled={!rescheduleAt || reschedule.isPending} onClick={() => reschedule.mutate(detail)}>Reagendar</button><RequestFeedback error={reschedule.error} /></div>}</section>}
  </ProtectedShell>;
}
function Select({ label, value, values, onChange }: { label: string; value: string; values: string[][]; onChange: (value: string) => void }) { return <label className="grid gap-1 text-sm font-medium">{label}<select className="rounded border p-2" value={value} onChange={event => onChange(event.target.value)}><option value="">Selecione</option>{values.map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></label>; }
