import { notFound } from "next/navigation";

const concepts = [
  { id: "A", name: "Conversation + Calendar", meaning: "Conversa, disponibilidade e confirmação.", tone: "bg-slate-950" },
  { id: "B", name: "IR Monogram", meaning: "Monograma geométrico de IA Recepção.", tone: "bg-brand-600" },
  { id: "C", name: "Smart Reception", meaning: "Mensagem → organização → confirmação.", tone: "bg-slate-50" },
  { id: "D", name: "Care + Connection", meaning: "Paciente, equipe e clínica conectados.", tone: "bg-brand-50" },
  { id: "E", name: "Pulse / Flow", meaning: "Fluxo contínuo da conversa à recepção.", tone: "bg-slate-950" },
];

export default function BrandReviewPage() {
  if (process.env.NODE_ENV === "production") notFound();
  return <main className="min-h-screen bg-slate-100 px-5 py-12 text-slate-950"><div className="mx-auto max-w-7xl"><p className="text-sm font-semibold uppercase tracking-[.18em] text-brand-600">Development only · Brand Review</p><h1 className="mt-3 text-4xl font-semibold tracking-tight">IA Recepção</h1><p className="mt-4 max-w-2xl text-slate-600">Comparação conceitual. Nenhuma alternativa abaixo é logo final. A escolha está marcada como APPROVAL REQUIRED.</p><div className="mt-10 grid gap-5 lg:grid-cols-2">{concepts.map(concept => <article className="overflow-hidden rounded-panel border border-slate-200 bg-white shadow-panel" key={concept.id}><div className={`grid min-h-52 place-items-center ${concept.tone}`}><ConceptMark id={concept.id} /></div><div className="p-6"><div className="flex items-center justify-between gap-3"><h2 className="text-xl font-semibold">{concept.id} — {concept.name}</h2><span className="rounded-full bg-amber-100 px-3 py-1 text-xs font-semibold text-amber-900">APPROVAL REQUIRED</span></div><p className="mt-2 text-slate-600">{concept.meaning}</p><div className="mt-5 grid gap-3 text-sm sm:grid-cols-2"><Preview label="Wordmark"><span className="font-semibold">IA Recepção</span></Preview><Preview label="Lockup"><span className="font-semibold">[mark] IA Recepção</span></Preview><Preview label="Favicon"><span className="grid size-8 place-items-center rounded bg-brand-600 text-xs font-bold text-white">{concept.id === "B" ? "IR" : concept.id}</span></Preview><Preview label="Monocromático"><span className="grid size-8 place-items-center rounded bg-slate-950 text-xs font-bold text-white">{concept.id}</span></Preview></div><p className="mt-5 text-xs text-slate-500">Aplicações a avaliar: navbar · login · sidebar · Landing Hero · dark · light · 16/32/64px.</p></div></article>)}</div><p className="mt-8 rounded-control border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950">Não aplicar nenhuma direção sem aprovação humana explícita.</p></div></main>;
}

function Preview({ label, children }: { label: string; children: React.ReactNode }) { return <div className="flex items-center justify-between rounded-control border border-slate-200 p-3"><span className="text-slate-500">{label}</span>{children}</div>; }
function ConceptMark({ id }: { id: string }) { if (id === "B") return <div className="text-7xl font-black tracking-tighter text-white">IR</div>; if (id === "C") return <div className="flex items-center gap-3"><span className="size-8 rounded-full bg-brand-600" /><span className="size-8 rounded-full bg-brand-400" /><span className="size-8 rounded-full bg-emerald-400" /></div>; if (id === "D") return <div className="grid size-28 place-items-center rounded-full border-8 border-brand-300 text-4xl text-brand-600">•</div>; if (id === "E") return <div className="text-7xl font-light text-brand-300">⌁</div>; return <div className="grid size-28 place-items-center rounded-3xl border-4 border-brand-300 text-5xl text-brand-300">✓</div>; }
