"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { LoadingRow, RequestFeedback } from "@/components/request-feedback";
import { ProtectedShell } from "@/components/protected-shell";
import { UnitForm } from "@/features/catalog/catalog-forms";
import { catalogApi } from "@/lib/api/catalog";
import { can } from "@/lib/auth/permissions";
import type { Unit, UnitDetail } from "@/lib/api/types";
import { useApi, useAuth } from "@/providers/providers";

export default function UnitsPage() {
  const api = useApi(); const { user } = useAuth(); const queryClient = useQueryClient(); const units = useQuery({ queryKey: ["units"], queryFn: () => catalogApi.listUnits(api) }); const [editing, setEditing] = useState<Unit | null | undefined>(); const [selected, setSelected] = useState<UnitDetail | null>(null); const allowed = can(user, "manageCatalog");
  const status = useMutation({ mutationFn: ({ id, next }: { id: string; next: "Active" | "Inactive" }) => catalogApi.setUnitStatus(api, id, next), onSuccess: () => queryClient.invalidateQueries({ queryKey: ["units"] }) });
  return <ProtectedShell><header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">Unidades</h1><p className="mt-1 text-slate-600">Gerencie unidades da clínica do tenant atual.</p></div>{allowed && <button className="rounded bg-blue-700 px-4 py-2 text-white" onClick={() => setEditing(null)}>Nova unidade</button>}</header>{editing !== undefined && allowed && <UnitForm unit={editing ?? undefined} onComplete={() => setEditing(undefined)} onCancel={() => setEditing(undefined)} />}<div className="mt-6 overflow-x-auto rounded bg-white shadow"><table className="w-full text-left"><thead><tr className="border-b"><th className="p-3">Nome</th><th className="p-3">Endereço</th><th className="p-3">Status</th><th className="p-3">Ações</th></tr></thead><tbody>{units.isLoading && <LoadingRow columns={4} />}{units.data?.map(unit => <tr className="border-b" key={unit.id}><td className="p-3">{unit.name}</td><td className="p-3">{unit.address}</td><td className="p-3">{unit.status}</td><td className="p-3"><button className="mr-3 text-blue-700 underline" onClick={async () => setSelected(await catalogApi.getUnitDetail(api, unit.id))}>Detalhes</button>{allowed && <><button className="mr-3 text-blue-700 underline" onClick={() => setEditing(unit)}>Editar</button><button className="text-blue-700 underline" onClick={() => status.mutate({ id: unit.id, next: unit.status === "Active" ? "Inactive" : "Active" })}>{unit.status === "Active" ? "Desativar" : "Ativar"}</button></>}</td></tr>)}</tbody></table><RequestFeedback error={units.error ?? status.error} /></div>{selected && <section className="mt-5 rounded bg-white p-4 shadow"><div className="flex justify-between"><h2 className="text-lg font-bold">{selected.unit.name}</h2><button className="underline" onClick={() => setSelected(null)}>Fechar</button></div><p className="mt-2 text-sm text-slate-600">Fuso horário da clínica: {selected.timeZone}</p><h3 className="mt-4 font-semibold">Horários de funcionamento</h3><p className="text-sm">{selected.businessHours.length ? selected.businessHours.map(hour => `${day(hour.dayOfWeek)} ${hour.opensAt}–${hour.closesAt}`).join(" · ") : "Não configurados"}</p><h3 className="mt-4 font-semibold">Profissionais vinculados</h3><ul className="list-disc pl-5 text-sm">{selected.professionals.map(professional => <li key={professional.id}>{professional.name} ({professional.status})</li>)}{selected.professionals.length === 0 && <li>Nenhum profissional vinculado.</li>}</ul></section>}</ProtectedShell>;
}

function day(value: number) { return ["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sáb"][value] ?? "—"; }
