import type { ApiClient } from "@/lib/api/client";
import type { AvailabilityRule, AvailabilityRuleRequest, Clinic, ClinicRequest, Professional, ProfessionalRequest, ProfessionalSchedule, SchedulePeriod, SchedulePeriodRequest, Specialty, SpecialtyDependencies, SpecialtyRequest, Unit, UnitDetail, UnitRequest } from "@/lib/api/types";

export const catalogApi = {
  getClinic: (api: ApiClient) => api.request<Clinic>("/api/clinics/current"),
  getClinicSetup: (api: ApiClient) => api.request<import("@/lib/api/types").PlatformOnboardingStatus>("/api/clinics/current/setup"),
  updateClinic: (api: ApiClient, request: ClinicRequest) => api.request<Clinic>("/api/clinics/current", { method: "PUT", body: JSON.stringify(request) }),
  listUnits: (api: ApiClient) => api.request<Unit[]>("/api/units"),
  getUnitDetail: (api: ApiClient, id: string) => api.request<UnitDetail>(`/api/units/${id}/details`),
  setUnitStatus: (api: ApiClient, id: string, status: "Active" | "Inactive") => api.request<void>(`/api/units/${id}/status/${status}`, { method: "POST" }),
  createUnit: (api: ApiClient, request: UnitRequest) => api.request<Unit>("/api/units", { method: "POST", body: JSON.stringify(request) }),
  updateUnit: (api: ApiClient, id: string, request: UnitRequest) => api.request<Unit>(`/api/units/${id}`, { method: "PUT", body: JSON.stringify(request) }),
  listSpecialties: (api: ApiClient) => api.request<Specialty[]>("/api/specialties"),
  createSpecialty: (api: ApiClient, request: SpecialtyRequest) => api.request<Specialty>("/api/specialties", { method: "POST", body: JSON.stringify(request) }),
  updateSpecialty: (api: ApiClient, id: string, request: SpecialtyRequest) => api.request<Specialty>(`/api/specialties/${id}`, { method: "PUT", body: JSON.stringify(request) }),
  getSpecialtyDependencies: (api: ApiClient, id: string) => api.request<SpecialtyDependencies>(`/api/specialties/${id}/dependencies`),
  setSpecialtyStatus: (api: ApiClient, id: string, status: "Active" | "Inactive") => api.request<void>(`/api/specialties/${id}/status/${status}`, { method: "POST" }),
  listProfessionals: (api: ApiClient) => api.request<Professional[]>("/api/professionals"),
  createProfessional: (api: ApiClient, request: ProfessionalRequest) => api.request<Professional>("/api/professionals", { method: "POST", body: JSON.stringify(request) }),
  updateProfessional: (api: ApiClient, id: string, request: ProfessionalRequest) => api.request<Professional>(`/api/professionals/${id}`, { method: "PUT", body: JSON.stringify(request) }),
  getProfessionalSchedule: (api: ApiClient, id: string, startsAt: string, endsAt: string) => api.request<ProfessionalSchedule>(`/api/professionals/${id}/schedule?startsAt=${encodeURIComponent(startsAt)}&endsAt=${encodeURIComponent(endsAt)}`),
  listAvailabilityRules: (api: ApiClient, id: string) => api.request<AvailabilityRule[]>(`/api/professionals/${id}/availability/rules`),
  addAvailabilityRule: (api: ApiClient, id: string, request: AvailabilityRuleRequest) => api.request<void>(`/api/professionals/${id}/availability`, { method: "POST", body: JSON.stringify(request) }),
  listScheduleBlocks: (api: ApiClient, id: string) => api.request<SchedulePeriod[]>(`/api/professionals/${id}/blocks`),
  addScheduleBlock: (api: ApiClient, id: string, request: SchedulePeriodRequest) => api.request<void>(`/api/professionals/${id}/blocks`, { method: "POST", body: JSON.stringify(request) }),
  deleteScheduleBlock: (api: ApiClient, id: string, blockId: string) => api.request<void>(`/api/professionals/${id}/blocks/${blockId}`, { method: "DELETE" }),
  listVacations: (api: ApiClient, id: string) => api.request<SchedulePeriod[]>(`/api/professionals/${id}/vacations`),
  addVacation: (api: ApiClient, id: string, request: SchedulePeriodRequest) => api.request<void>(`/api/professionals/${id}/vacations`, { method: "POST", body: JSON.stringify(request) }),
  deleteVacation: (api: ApiClient, id: string, vacationId: string) => api.request<void>(`/api/professionals/${id}/vacations/${vacationId}`, { method: "DELETE" }),
};
