"use client";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { ProtectedShell } from "@/components/protected-shell";
import { conversationsApi } from "@/lib/api/conversations";
import type { ConversationDetail } from "@/lib/api/types";
import { can } from "@/lib/auth/permissions";
import { useApi, useAuth } from "@/providers/providers";
import { Button } from "@/components/ui/button";
import { Card, StatusBadge } from "@/components/ui/surfaces";
import { Input, Select } from "@/components/ui/form";
import { PageContainer, PageHeader } from "@/components/ui/page";
import { EmptyState, ErrorState, Skeleton } from "@/components/ui/states";

export default function ConversationsPage() {
  const api = useApi(); const { user } = useAuth(); const client = useQueryClient(); const allowed = can(user, "manageOperations");
  const [search, setSearch] = useState(""); const [submittedSearch, setSubmittedSearch] = useState(""); const [selectedId, setSelectedId] = useState<string>();
  const conversations = useQuery({ queryKey: ["conversations", submittedSearch], queryFn: () => conversationsApi.list(api, 1, submittedSearch) }); const queue = useQuery({ enabled: allowed, queryKey: ["conversation-queue"], queryFn: () => conversationsApi.queue(api) });
  const detail = useQuery({ enabled: !!selectedId, queryKey: ["conversation", selectedId], queryFn: () => conversationsApi.detail(api, selectedId!) }); const messages = useQuery({ enabled: !!selectedId, queryKey: ["conversation-messages", selectedId], queryFn: () => conversationsApi.messages(api, selectedId!) }); const linkedAppointments = useQuery({ enabled: !!selectedId, queryKey: ["conversation-appointments", selectedId], queryFn: () => conversationsApi.appointments(api, selectedId!) }); const operators = useQuery({ enabled: allowed, queryKey: ["conversation-operators"], queryFn: () => conversationsApi.operators(api) });
  const refresh = async () => { await client.invalidateQueries({ queryKey: ["conversations"] }); await client.invalidateQueries({ queryKey: ["conversation-queue"] }); await client.invalidateQueries({ queryKey: ["conversation", selectedId] }); await client.invalidateQueries({ queryKey: ["conversation-messages", selectedId] }); await client.invalidateQueries({ queryKey: ["conversation-appointments", selectedId] }); };
  const operation = useMutation({ mutationFn: ({ action, item }: { action: "assign" | "release" | "pause" | "resume" | "close" | "reopen"; item: ConversationDetail }) => conversationsApi[action](api, item.id, item.version), onSuccess: refresh }); const priority = useMutation({ mutationFn: ({ item, value }: { item: ConversationDetail; value: string }) => conversationsApi.setPriority(api, item.id, item.version, value), onSuccess: refresh }); const manual = useMutation({ mutationFn: ({ item, content }: { item: ConversationDetail; content: string }) => conversationsApi.sendManualMessage(api, item.id, item.version, content), onSuccess: refresh }); const transfer = useMutation({ mutationFn: ({ item, userId }: { item: ConversationDetail; userId: string }) => conversationsApi.transfer(api, item.id, item.version, userId), onSuccess: refresh }); const markRead = useMutation({ mutationFn: ({ messageId, version }: { messageId: string; version: number }) => conversationsApi.markRead(api, selectedId!, messageId, version), onSuccess: refresh });
  return <ProtectedShell><PageContainer><PageHeader description="Acompanhe conversas, a fila humana e as ações de atendimento em tempo real." pathname="/conversations" title="Inbox de conversas" />
    {allowed && <Card className="mt-5 flex items-center justify-between border-amber-200 bg-amber-50"><div><p className="font-semibold text-amber-950">Fila humana</p><p className="text-sm text-amber-900">{queue.data?.totalCount ?? 0} conversa(s) aguardando atendimento.</p></div><StatusBadge tone="warning">Prioridade operacional</StatusBadge></Card>}
    <form className="mt-5 flex gap-2" onSubmit={event => { event.preventDefault(); setSubmittedSearch(search); }}><Input aria-label="Buscar conversa" onChange={event => setSearch(event.target.value)} placeholder="Buscar paciente ou telefone" value={search} /><Button type="submit" variant="outline">Buscar</Button></form>
    <section className="mt-5 grid gap-5 xl:grid-cols-[minmax(20rem,.8fr)_minmax(26rem,1.2fr)]"><Card className="p-0">{conversations.isError ? <ErrorState onRetry={() => void conversations.refetch()} /> : conversations.isLoading ? <Skeleton className="h-96" /> : conversations.data?.items.length === 0 ? <EmptyState description="Tente ajustar a busca para localizar conversas." title="Nenhuma conversa encontrada" /> : <ul className="divide-y divide-slate-100">{conversations.data?.items.map(item => <li key={item.id}><button className={`w-full p-4 text-left transition-colors hover:bg-slate-50 ${selectedId === item.id ? "bg-brand-50" : ""}`} onClick={() => setSelectedId(item.id)}><div className="flex items-center justify-between gap-3"><strong>{item.patientName}</strong><StatusBadge tone={item.priority === "Urgent" ? "danger" : item.priority === "High" ? "warning" : "neutral"}>{item.priority}</StatusBadge></div><p className="mt-1 text-sm text-slate-500">{item.maskedPhone} · {item.status} · {item.automationMode}</p></button></li>)}</ul>}</Card><ConversationPanel allowed={allowed} appointments={linkedAppointments.data ?? []} busy={operation.isPending || priority.isPending || manual.isPending || transfer.isPending || markRead.isPending} detail={detail.data} messages={messages.data?.items ?? []} operators={operators.data ?? []} onAction={action => detail.data && operation.mutate({ action, item: detail.data })} onManual={content => detail.data && manual.mutate({ item: detail.data, content })} onPriority={value => detail.data && priority.mutate({ item: detail.data, value })} onRead={messageId => detail.data && markRead.mutate({ messageId, version: detail.data.version })} onTransfer={userId => detail.data && transfer.mutate({ item: detail.data, userId })} /></section>
  </PageContainer></ProtectedShell>;
}

function ConversationPanel({ appointments, detail, messages, operators, allowed, busy, onAction, onPriority, onManual, onRead, onTransfer }: { appointments: { id: string; startsAt: string; status: string; specialtyName: string; professionalName: string }[]; detail?: ConversationDetail; messages: { id: string; direction: string; contentSanitized?: string | null; status: string; createdAt: string; readAt?: string | null }[]; operators: { id: string; name: string; role: string }[]; allowed: boolean; busy: boolean; onAction: (action: "assign" | "release" | "pause" | "resume" | "close" | "reopen") => void; onPriority: (value: string) => void; onManual: (value: string) => void; onRead: (messageId: string) => void; onTransfer: (userId: string) => void }) {
  const [content, setContent] = useState(""); const [target, setTarget] = useState("");
  if (!detail) return <EmptyState description="Escolha uma conversa na lista para abrir o histórico e as ações disponíveis." title="Selecione uma conversa" />;
  const paused = detail.automationMode === "Paused"; const closed = detail.status === "Closed";
  return <Card><header className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold">{detail.patientName}</h2><p className="mt-1 text-sm text-slate-600">{detail.status} · automação {detail.automationMode}</p></div><StatusBadge tone={closed ? "neutral" : "info"}>{detail.priority}</StatusBadge></header>
    {allowed && <div className="mt-4 flex flex-wrap gap-2"><Button disabled={busy} onClick={() => onAction("assign")} size="sm" variant="outline">Assumir</Button><Button disabled={busy} onClick={() => onAction("release")} size="sm" variant="ghost">Liberar</Button><Button disabled={busy} onClick={() => onAction(paused ? "resume" : "pause")} size="sm" variant="outline">{paused ? "Retomar" : "Pausar"}</Button><Button disabled={busy} onClick={() => onAction(closed ? "reopen" : "close")} size="sm" variant="outline">{closed ? "Reabrir" : "Encerrar"}</Button><Select aria-label="Prioridade" className="w-auto" disabled={busy} onChange={event => onPriority(event.target.value)} value={detail.priority}><option value="Normal">Normal</option><option value="High">Alta</option><option value="Urgent">Urgente</option></Select><Select aria-label="Transferir conversa" className="w-auto" disabled={busy} onChange={event => setTarget(event.target.value)} value={target}><option value="">Transferir para...</option>{operators.map(operator => <option key={operator.id} value={operator.id}>{operator.name}</option>)}</Select><Button disabled={busy || !target} onClick={() => onTransfer(target)} size="sm" variant="outline">Transferir</Button></div>}
    <div className="mt-5 grid gap-3">{messages.map(message => <article className={`max-w-[85%] rounded-panel p-3 text-sm ${message.direction === "Inbound" ? "bg-slate-100" : "ml-auto bg-brand-50"}`} key={message.id}><p>{message.contentSanitized || "Conteúdo indisponível"}</p><div className="mt-1 flex items-center gap-2 text-xs text-slate-500"><span>{new Date(message.createdAt).toLocaleString("pt-BR")} · {message.status}</span>{allowed && message.direction === "Inbound" && !message.readAt && <Button disabled={busy} onClick={() => onRead(message.id)} size="sm" variant="ghost">Marcar como lida</Button>}</div></article>)}{messages.length === 0 && <p className="text-sm text-slate-600">Sem mensagens disponíveis.</p>}</div>
    <section className="mt-5 border-t border-slate-200 pt-4"><h3 className="text-sm font-semibold text-slate-900">Consultas vinculadas</h3>{appointments.length === 0 ? <p className="mt-2 text-sm text-slate-600">Nenhuma consulta vinculada a esta conversa.</p> : <ul className="mt-2 grid gap-2">{appointments.map(appointment => <li className="rounded-control bg-slate-50 p-3 text-sm text-slate-700" key={appointment.id}><strong>{new Date(appointment.startsAt).toLocaleString("pt-BR")}</strong><span className="ml-2">{appointment.specialtyName} · {appointment.professionalName} · {appointment.status}</span></li>)}</ul>}</section>
    {allowed && !closed && <form className="mt-5 flex gap-2 border-t pt-4" onSubmit={event => { event.preventDefault(); if (content.trim()) { onManual(content); setContent(""); } }}><Input aria-label="Mensagem manual" onChange={event => setContent(event.target.value)} placeholder="Digite uma mensagem" value={content} /><Button disabled={busy || !content.trim()} type="submit">Enviar</Button></form>}</Card>;
}
