"use client";

import { useState } from "react";
import { ValueCalculator } from "@/components/landing/value-calculator";
import { trackPublicEvent } from "@/lib/analytics/public-events";

type ProductTab = "Dashboard" | "Agenda" | "Conversas";

const tabs: ProductTab[] = ["Dashboard", "Agenda", "Conversas"];

export function ProductShowcase() {
  const [active, setActive] = useState<ProductTab>("Dashboard");
  const selectTab = (tab: ProductTab) => { setActive(tab); trackPublicEvent("product_tab_changed", { tab }); };
  const handleTabKeyDown = (event: React.KeyboardEvent<HTMLButtonElement>) => { const current = tabs.indexOf(active); if (event.key === "ArrowRight" || event.key === "ArrowDown") { event.preventDefault(); selectTab(tabs[(current + 1) % tabs.length]); } if (event.key === "ArrowLeft" || event.key === "ArrowUp") { event.preventDefault(); selectTab(tabs[(current - 1 + tabs.length) % tabs.length]); } };
  return <section className="bg-slate-50 text-slate-950" id="showcase"><div className="mx-auto max-w-content px-5 py-20 lg:px-8"><div className="max-w-2xl"><p className="text-sm font-semibold uppercase tracking-[.18em] text-brand-600">Product showcase</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Uma visão completa da operação.</h2><p className="mt-4 text-lg leading-8 text-slate-600">WhatsApp, agenda e recepção compartilham o mesmo contexto operacional.</p></div><div className="mt-8 flex flex-wrap gap-2" role="tablist" aria-label="Superfícies do produto">{tabs.map(tab => <button aria-controls={`showcase-${tab.toLowerCase()}`} aria-selected={active === tab} className={`rounded-control px-4 py-2 text-sm font-semibold focus:outline-none focus:ring-2 focus:ring-brand-500 ${active === tab ? "bg-brand-600 text-white" : "border border-slate-300 bg-white text-slate-700 hover:border-brand-400"}`} id={`tab-${tab.toLowerCase()}`} key={tab} onClick={() => selectTab(tab)} onKeyDown={handleTabKeyDown} role="tab" tabIndex={active === tab ? 0 : -1} type="button">{tab}</button>)}</div><div className="mt-5 overflow-hidden rounded-panel border border-slate-200 bg-white shadow-floating" id={`showcase-${active.toLowerCase()}`} role="tabpanel" aria-labelledby={`tab-${active.toLowerCase()}`} aria-live="polite"><div className="flex items-center gap-2 border-b border-slate-200 bg-slate-100 px-5 py-3"><span className="h-2.5 w-2.5 rounded-full bg-red-300" /><span className="h-2.5 w-2.5 rounded-full bg-amber-300" /><span className="h-2.5 w-2.5 rounded-full bg-emerald-300" /><span className="ml-3 text-xs text-slate-500">app.iarecepcao.com.br / {active.toLowerCase()}</span></div><ShowcaseSurface active={active} /></div><BentoGrid /><ValueCalculator /></div></section>;
}

function BentoGrid() {
  return <div className="mt-16"><p className="text-sm font-semibold uppercase tracking-[.18em] text-brand-600">Operação em um só lugar</p><div className="mt-4 grid gap-4 md:grid-cols-3 md:grid-rows-2"><article className="rounded-panel bg-slate-950 p-6 text-white md:col-span-2"><p className="text-sm text-brand-300">WhatsApp</p><h3 className="mt-8 text-2xl font-semibold">Conversa que vira próximo passo.</h3><p className="mt-3 max-w-lg text-slate-300">O paciente pergunta, a disponibilidade aparece e a recepção acompanha o contexto.</p></article><article className="rounded-panel border border-slate-200 bg-white p-6 md:row-span-2"><p className="text-sm text-brand-600">Agenda</p><h3 className="mt-8 text-xl font-semibold">Horários organizados.</h3><div className="mt-6 grid grid-cols-5 gap-2">{Array.from({ length: 15 }, (_, index) => <span className={`h-8 rounded ${index === 7 ? "bg-brand-500" : "bg-slate-100"}`} key={index} />)}</div><p className="mt-6 text-sm leading-6 text-slate-600">Dia, semana, mês, lista, bloqueios e disponibilidade.</p></article><article className="rounded-panel border border-slate-200 bg-brand-50 p-6"><p className="text-sm text-brand-700">Fila humana</p><h3 className="mt-6 text-xl font-semibold text-brand-950">Handoff sem perder contexto.</h3><p className="mt-2 text-sm leading-6 text-brand-900">A recepção assume quando necessário.</p></article><article className="rounded-panel border border-slate-200 bg-white p-6"><p className="text-sm text-brand-600">Dashboard</p><h3 className="mt-6 text-xl font-semibold">Decisão com visibilidade.</h3><p className="mt-2 text-sm leading-6 text-slate-600">KPIs, alertas e próximas consultas.</p></article></div></div>;
}

function ShowcaseSurface({ active }: { active: ProductTab }) {
  if (active === "Agenda") return <div className="grid gap-5 bg-slate-100 p-5 md:grid-cols-[.75fr_1.8fr]"><div className="space-y-3"><div className="h-4 w-28 rounded bg-slate-300" /><div className="h-9 rounded border border-slate-200 bg-white" /><div className="h-9 rounded border border-slate-200 bg-white" /><div className="h-9 rounded border border-slate-200 bg-white" /><div className="grid grid-cols-2 gap-2"><div className="h-8 rounded bg-brand-600" /><div className="h-8 rounded border border-slate-200 bg-white" /></div></div><div className="rounded-control border border-slate-200 bg-white p-3"><div className="mb-3 flex items-center justify-between"><span className="h-3 w-24 rounded bg-slate-200" /><span className="h-7 w-20 rounded bg-brand-600" /></div><div className="grid grid-cols-7 gap-1 text-[9px] text-slate-400">{["Seg", "Ter", "Qua", "Qui", "Sex", "Sáb", "Dom"].map(day => <span className="text-center" key={day}>{day}</span>)}</div><div className="mt-2 grid grid-cols-7 gap-1">{Array.from({ length: 35 }, (_, index) => <span className={`h-8 rounded p-1 text-[9px] ${index === 17 ? "bg-brand-600 text-white" : index === 18 || index === 19 ? "bg-brand-50 text-brand-700" : "bg-slate-50 text-slate-500"}`} key={index}>{(index % 28) + 1}</span>)}</div></div></div>;
  if (active === "Conversas") return <div className="grid gap-4 bg-slate-100 p-5 md:grid-cols-[.8fr_1.6fr]"><div className="space-y-2">{["Paciente Minimal 1", "Paciente Minimal 2", "Felipe Eduardo", "Fila humana"].map((item, index) => <div className={`rounded-control border p-3 text-sm ${index === 2 ? "border-brand-300 bg-brand-50" : "border-slate-200 bg-white"}`} key={item}><strong>{item}</strong><span className="mt-1 block text-xs text-slate-500">{index === 3 ? "Aguardando atendimento" : "WhatsApp · hoje"}</span></div>)}</div><div className="rounded-control border border-slate-200 bg-white p-4"><div className="flex items-center justify-between border-b border-slate-100 pb-3"><div><p className="font-semibold">Felipe Eduardo</p><p className="text-xs text-slate-500">Bot · automação</p></div><span className="rounded-full bg-brand-50 px-2 py-1 text-xs text-brand-700">Normal</span></div><div className="mt-4 space-y-3 text-sm"><p className="max-w-[80%] rounded-control bg-slate-100 p-3">Tem cardiologista amanhã?</p><p className="ml-auto max-w-[80%] rounded-control bg-brand-100 p-3 text-brand-950">Encontrei horários. Qual você prefere?</p><p className="max-w-[80%] rounded-control bg-slate-100 p-3">10:30</p><p className="ml-auto max-w-[80%] rounded-control bg-brand-100 p-3 text-brand-950">Posso confirmar?</p></div></div></div>;
  return <div className="bg-slate-100 p-5"><div className="grid gap-3 sm:grid-cols-4">{[["Consultas", "24"], ["Pendentes", "6"], ["Fila humana", "3"], ["Falhas WhatsApp", "1"]].map(([label, value]) => <div className="rounded-control border border-slate-200 bg-white p-4" key={label}><span className="block text-xs text-slate-500">{label}</span><strong className="mt-2 block text-2xl text-slate-950">{value}</strong></div>)}</div><div className="mt-5 grid gap-4 md:grid-cols-[1.3fr_.7fr]"><div className="h-36 rounded-control border border-slate-200 bg-white p-4"><p className="text-xs text-slate-500">Consultas por período</p><div className="mt-4 flex h-24 items-end gap-2">{[38, 52, 44, 68, 58, 82, 72, 90].map((height, index) => <span className="flex-1 rounded-t bg-brand-500" key={index} style={{ height: `${height}%` }} />)}</div></div><div className="rounded-control border border-slate-200 bg-white p-4"><p className="text-sm font-semibold">Atenção necessária</p><p className="mt-3 text-sm text-slate-600">1 falha de envio aguarda análise.</p><span className="mt-4 block h-2 rounded-full bg-emerald-400" /></div></div></div>;
}
