"use client";

import { useMemo, useState } from "react";
import { calculateOperationalImpact, type ValueCalculatorInputs } from "@/lib/commercial/value-calculator";

const currency = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });
const number = new Intl.NumberFormat("pt-BR", { maximumFractionDigits: 1 });

export function ValueCalculator() {
  const [inputs, setInputs] = useState<ValueCalculatorInputs>({ attendants: 2, monthlyTeamCost: 6000, requestsPerDay: 30, minutesPerRequest: 4, workDays: 22, automatablePercent: 40, monthlyInvestment: 0 });
  const result = useMemo(() => calculateOperationalImpact(inputs), [inputs]);
  const update = (key: keyof ValueCalculatorInputs) => (event: React.ChangeEvent<HTMLInputElement>) => setInputs(current => ({ ...current, [key]: Number(event.target.value) }));
  return <section className="bg-white text-slate-950" id="impacto"><div className="mx-auto max-w-content px-5 py-20 lg:px-8"><div className="max-w-2xl"><p className="text-sm font-semibold uppercase tracking-[.18em] text-brand-600">Valor potencial</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Calcule quanto tempo da sua equipe hoje é consumido por tarefas repetitivas.</h2><p className="mt-4 text-lg leading-8 text-slate-600">Ajuste as premissas para construir uma estimativa operacional transparente.</p></div><div className="mt-10 grid gap-6 lg:grid-cols-[.9fr_1.1fr]"><div className="grid gap-4 rounded-panel border border-slate-200 bg-slate-50 p-6">{[["attendants", "Atendentes", 1, 20], ["monthlyTeamCost", "Custo mensal da equipe (R$)", 0, 100000], ["requestsPerDay", "Solicitações repetitivas/dia", 0, 1000], ["minutesPerRequest", "Minutos por solicitação", 0, 120], ["workDays", "Dias úteis/mês", 1, 31], ["automatablePercent", "Percentual potencialmente automatizável (%)", 0, 100], ["monthlyInvestment", "Investimento mensal (R$)", 0, 100000]].map(([key, label, min, max]) => <label className="grid gap-1 text-sm font-medium text-slate-700" key={key as string}>{label}<input className="h-10 rounded-control border border-slate-300 bg-white px-3 text-slate-950" min={min as number} max={max as number} onChange={update(key as keyof ValueCalculatorInputs)} step="any" type="number" value={inputs[key as keyof ValueCalculatorInputs]} /></label>)}</div><div className="rounded-panel border border-brand-dark-border bg-brand-dark p-6 text-white"><p className="text-sm uppercase tracking-[.18em] text-brand-300">Impacto operacional estimado</p><div className="mt-6 grid gap-4 sm:grid-cols-2"><Metric label="Horas potencialmente liberadas/mês" value={number.format(result.releasedHours)} /><Metric label="Valor equivalente de tempo" value={currency.format(result.timeValue)} /><Metric label="Investimento informado" value={currency.format(inputs.monthlyInvestment)} /><Metric label="Diferença estimada" value={currency.format(result.estimatedImpact)} /></div><p className="mt-6 text-sm leading-6 text-slate-300">Estimativa baseada nas informações fornecidas. Resultados reais dependem da operação, adesão, volume de atendimentos e configuração da clínica.</p></div></div></div></section>;
}

function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-control border border-brand-dark-border bg-brand-dark-surface p-4"><span className="block text-sm text-slate-300">{label}</span><strong className="mt-2 block text-2xl text-white">{value}</strong></div>; }
