"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { ProtectedShell } from "@/components/protected-shell";
import { Button } from "@/components/ui/button";
import { ErrorState, Skeleton } from "@/components/ui/states";
import { Icon } from "@/components/ui/icon";
import { PageContainer, PageHeader } from "@/components/ui/page";
import { Card, StatCard, StatusBadge } from "@/components/ui/surfaces";
import type { DashboardSummary, IntegrationStatus, PlatformDashboard } from "@/lib/api/types";
import { platformApi } from "@/lib/api/platform";
import { dashboardCustomRange, dashboardPeriodLabels, dashboardPeriodRange, type DashboardPeriod } from "@/lib/dashboard/period";
import { useApi, useAuth } from "@/providers/providers";


function ActionCard({ href, label, value, description, icon }: { href: string; label: string; value: string; description: string; icon: "calendar" | "messages" | "whatsapp" | "audit" }) {
  return <Link className="block rounded-panel focus:outline-none focus:ring-2 focus:ring-brand-500" href={href}><StatCard label={label} value={value} description={description}><Icon className="text-brand-600" name={icon} /></StatCard></Link>;
}

function ClinicDashboardPage() {
  const api = useApi();
  const { realtimeStatus } = useAuth();
  const [period, setPeriod] = useState<DashboardPeriod>("today");
  const today = new Date().toISOString().slice(0, 10);
  const [customFrom, setCustomFrom] = useState(today);
  const [customTo, setCustomTo] = useState(today);
  const range = useMemo(() => period === "custom" ? dashboardCustomRange(customFrom, customTo) ?? dashboardPeriodRange("today") : dashboardPeriodRange(period), [period, customFrom, customTo]);
  useEffect(() => { const params = new URLSearchParams(window.location.search); const value = params.get("period"); if (value === "today" || value === "7d" || value === "30d" || value === "month" || value === "custom") setPeriod(value); if (params.get("from")) setCustomFrom(params.get("from")!); if (params.get("to")) setCustomTo(params.get("to")!); }, []);
  useEffect(() => { const params = new URLSearchParams({ period }); if (period === "custom") { params.set("from", customFrom); params.set("to", customTo); } window.history.replaceState(null, "", `/dashboard?${params.toString()}`); }, [period, customFrom, customTo]);
  const integration = useQuery({ queryKey: ["integration-status"], queryFn: () => api.request<IntegrationStatus>("/api/whatsapp/integration/status") });
  const dashboard = useQuery({ queryKey: ["dashboard", range], queryFn: () => api.request<DashboardSummary>(`/api/dashboard?from=${encodeURIComponent(range.from)}&to=${encodeURIComponent(range.to)}`) });
  const summary = dashboard.data;
  const hasError = integration.isError || dashboard.isError;
  const attentionCount = (summary?.failedOutboxMessages ?? 0) + (summary?.waitingHumanConversations ?? 0);

  return <ProtectedShell><PageContainer><PageHeader actions={<div className="grid gap-2 sm:flex sm:flex-wrap sm:items-center" role="group" aria-label="Período do dashboard"><div className="flex flex-wrap gap-2">{(Object.keys(dashboardPeriodLabels) as DashboardPeriod[]).map(item => <Button aria-pressed={period === item} key={item} onClick={() => setPeriod(item)} size="sm" variant={period === item ? "primary" : "outline"}>{dashboardPeriodLabels[item]}</Button>)}</div>{period === "custom" && <div className="flex flex-wrap items-end gap-2 text-sm"><label className="grid gap-1 text-slate-600">De<input aria-label="Data inicial" className="h-9 rounded-control border border-slate-300 px-2 text-slate-900" onChange={event => setCustomFrom(event.target.value)} type="date" value={customFrom} /></label><label className="grid gap-1 text-slate-600">Até<input aria-label="Data final" className="h-9 rounded-control border border-slate-300 px-2 text-slate-900" onChange={event => setCustomTo(event.target.value)} type="date" value={customTo} /></label></div>}</div>} description="Uma visão operacional do tenant atual, com dados agregados no backend." pathname="/dashboard" title="Dashboard executivo" />
    {hasError && <div className="mt-6"><ErrorState onRetry={() => { void integration.refetch(); void dashboard.refetch(); }} title="Não foi possível carregar o dashboard" /></div>}
    <Card className="mt-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold text-slate-950">WhatsApp no período</h2><p className="mt-1 text-sm text-slate-600">Mensagens e conversas abertas com dados reais do período selecionado.</p></div><Link className="text-sm font-medium text-brand-700 hover:underline" href="/integrations/whatsapp">Operar WhatsApp</Link></div><div className="mt-5 grid grid-cols-2 gap-3 text-sm sm:grid-cols-4"><div className="rounded-control bg-slate-50 p-3"><span className="block text-slate-500">Recebidas</span><strong className="text-lg text-slate-950">{summary?.whatsAppMetrics?.messagesReceived ?? "—"}</strong></div><div className="rounded-control bg-slate-50 p-3"><span className="block text-slate-500">Enviadas</span><strong className="text-lg text-slate-950">{summary?.whatsAppMetrics?.messagesSent ?? "—"}</strong></div><div className="rounded-control bg-red-50 p-3"><span className="block text-red-700">Falhas</span><strong className="text-lg text-red-900">{summary?.whatsAppMetrics?.failedMessages ?? "—"}</strong></div><div className="rounded-control bg-amber-50 p-3"><span className="block text-amber-700">Abertas</span><strong className="text-lg text-amber-950">{summary?.whatsAppMetrics?.openConversations ?? "—"}</strong></div></div></Card>
    <section className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-3" aria-label="Indicadores operacionais">{dashboard.isLoading ? Array.from({ length: 6 }, (_, index) => <Skeleton className="h-32" key={index} />) : <><ActionCard description={`Período: ${dashboardPeriodLabels[period]}`} href="/appointments" icon="calendar" label="Consultas" value={summary ? String(summary.appointmentsToday) : "—"} /><ActionCard description="Aguardando confirmação" href="/appointments?status=Pending" icon="calendar" label="Pendentes" value={summary ? String(summary.pendingAppointmentsToday) : "—"} /><ActionCard description="Conversas aguardando recepção" href="/conversations?queue=waiting" icon="messages" label="Fila humana" value={summary ? String(summary.waitingHumanConversations) : "—"} /><ActionCard description="Conversas não encerradas" href="/conversations" icon="messages" label="Conversas ativas" value={summary ? String(summary.activeConversations) : "—"} /><ActionCard description="Mensagens que exigem atenção" href="/integrations/whatsapp" icon="whatsapp" label="Falhas WhatsApp" value={summary ? String(summary.failedOutboxMessages) : "—"} /><StatCard description={integration.data?.status ?? "Sem configuração ativa"} label="Status WhatsApp" value={integration.isLoading ? "…" : integration.data?.status ?? "Não configurado"}><StatusBadge tone={integration.data?.status === "Conectado" ? "success" : "warning"}>WhatsApp</StatusBadge></StatCard></>}</section>
    <section className="mt-6 grid gap-6 lg:grid-cols-2"><Card><h2 className="font-semibold text-slate-950">Consultas por status</h2><p className="mt-1 text-sm text-slate-600">Distribuição agregada no período selecionado.</p><div className="mt-5 grid gap-3">{Object.entries(summary?.appointmentStatus ?? {}).length ? Object.entries(summary?.appointmentStatus ?? {}).map(([status, value]) => { const total = summary?.appointmentsToday || 1; const width = Math.min(100, Math.round((value / total) * 100)); return <div key={status}><div className="flex justify-between text-sm"><span>{status}</span><strong>{value}</strong></div><div className="mt-1 h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-brand-500" style={{ width: `${width}%` }} /></div></div>; }) : <p className="text-sm text-slate-600">Nenhuma consulta no período.</p>}</div></Card><Card><div className="flex items-start justify-between gap-4"><div><h2 className="font-semibold text-slate-950">Atenção necessária</h2><p className="mt-1 text-sm text-slate-600">Itens reais que podem exigir ação da equipe.</p></div><StatusBadge tone={attentionCount ? "warning" : "success"}>{attentionCount ? `${attentionCount} item(ns)` : "Tudo certo"}</StatusBadge></div><div className="mt-5 grid gap-3 text-sm">{summary?.failedOutboxMessages ? <Link className="rounded-control bg-red-50 p-3 text-red-900 hover:bg-red-100" href="/integrations/whatsapp">{summary.failedOutboxMessages} falha(s) de envio aguardam análise.</Link> : null}{summary?.waitingHumanConversations ? <Link className="rounded-control bg-amber-50 p-3 text-amber-950 hover:bg-amber-100" href="/conversations?queue=waiting">{summary.waitingHumanConversations} conversa(s) aguardam atendimento humano.</Link> : null}{attentionCount === 0 && <p className="text-slate-600">Nenhum alerta operacional no período selecionado.</p>}</div></Card></section>
    <section className="mt-6 grid gap-6 lg:grid-cols-2"><Card><div className="flex items-start justify-between gap-4"><div><h2 className="font-semibold text-slate-950">Próximas consultas</h2><p className="mt-1 text-sm text-slate-600">As cinco próximas consultas disponíveis.</p></div><Link className="text-sm font-medium text-brand-700 hover:underline" href="/appointments">Ver agenda</Link></div><div className="mt-5 grid gap-2">{dashboard.isLoading ? <Skeleton className="h-20" /> : summary?.upcomingAppointments?.length ? summary.upcomingAppointments.map(item => <Link className="grid gap-1 rounded-control border border-slate-200 p-3 text-sm hover:bg-slate-50 sm:grid-cols-[5rem_1fr_auto] sm:items-center sm:gap-3" href={`/appointments?date=${item.startsAt.slice(0, 10)}&view=day`} key={item.id}><time className="font-semibold text-slate-700">{new Date(item.startsAt).toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit" })}</time><span className="truncate"><strong>{item.patientName}</strong><span className="block text-xs text-slate-500">{item.professionalName} · {item.unitName}</span></span><StatusBadge tone={item.status === "Confirmed" ? "success" : item.status === "Cancelled" ? "danger" : "warning"}>{item.status}</StatusBadge></Link>) : <p className="text-sm text-slate-600">Nenhuma consulta nos próximos sete dias.</p>}</div></Card><Card><div className="flex items-start justify-between gap-4"><div><h2 className="font-semibold text-slate-950">Acesso rápido</h2><p className="mt-1 text-sm text-slate-600">Continue a operação a partir dos indicadores.</p></div><StatusBadge tone={realtimeStatus === "online" ? "success" : "warning"}>{realtimeStatus === "online" ? "Realtime conectado" : "Realtime limitado"}</StatusBadge></div><div className="mt-5 grid gap-2 sm:grid-cols-2"><Link className="rounded-control border border-slate-200 p-3 text-sm font-medium hover:bg-slate-50" href="/appointments">Ver agenda</Link><Link className="rounded-control border border-slate-200 p-3 text-sm font-medium hover:bg-slate-50" href="/conversations">Abrir conversas</Link><Link className="rounded-control border border-slate-200 p-3 text-sm font-medium hover:bg-slate-50" href="/integrations/whatsapp">Operar WhatsApp</Link><Link className="rounded-control border border-slate-200 p-3 text-sm font-medium hover:bg-slate-50" href="/audit">Consultar auditoria</Link></div></Card></section>
    <Card className="mt-6"><h2 className="font-semibold text-slate-950">Métricas avançadas</h2><p className="mt-1 max-w-2xl text-sm text-slate-600">Tendências, ocupação por profissional, horários de maior procura e funil de conversão ainda dependem de eventos agregados que não existem no contrato atual. Nenhum número estimado é exibido.</p></Card>
  </PageContainer></ProtectedShell>;
}

function PlatformDashboardPage() {
  const api = useApi();
  const [period, setPeriod] = useState<"7d" | "30d" | "90d">("30d");
  const dashboard = useQuery({ queryKey: ["platform-dashboard", period], queryFn: () => platformApi.dashboard(api, period) });
  const data = dashboard.data;
  const maxGrowth = Math.max(1, ...(data?.growth.map(item => item.newClinics) ?? [1]));
  const funnel = data?.commercial;
  return <PageContainer><PageHeader pathname="/dashboard" title="Visão da plataforma" description="Acompanhe a saúde comercial e operacional das clínicas cadastradas." actions={<div className="flex flex-wrap gap-2"><Link href="/platform/onboarding" className="rounded-control bg-brand-600 px-4 py-2 text-sm font-semibold text-white">Nova clínica</Link><Link href="/platform/leads" className="rounded-control border border-slate-300 px-4 py-2 text-sm font-semibold text-slate-800">Ver leads</Link></div>} />
    <div className="mt-6 flex flex-wrap items-center justify-between gap-3"><div className="flex gap-2" role="group" aria-label="Período"><span className="sr-only">Período</span>{(["7d", "30d", "90d"] as const).map(value => <Button key={value} size="sm" variant={period === value ? "primary" : "outline"} aria-pressed={period === value} onClick={() => setPeriod(value)}>{value.replace("d", " dias")}</Button>)}</div><Button size="sm" variant="outline" onClick={() => void dashboard.refetch()}>Atualizar</Button></div>
    {dashboard.isError && <div className="mt-6"><ErrorState onRetry={() => void dashboard.refetch()} title="Não foi possível carregar a visão da plataforma" /></div>}
    {dashboard.isLoading && <section className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{Array.from({ length: 4 }, (_, index) => <Skeleton className="h-28" key={index} />)}</section>}
    {data && <><section className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4" aria-label="Indicadores da plataforma"><StatCard label="Clínicas ativas" value={String(data.summary.activeClinics)} description={`${data.summary.totalClinics} no total`} /><StatCard label="Em configuração" value={String(data.summary.provisioningClinics)} description="Setup pendente" /><StatCard label="Novas clínicas" value={String(data.summary.newClinics)} description={`Nos últimos ${period.replace("d", " dias")}`} /><StatCard label="Leads aguardando contato" value={String(data.commercial.awaitingContact)} description={`${data.commercial.totalInPeriod} leads no período`} /></section>
      <section className="mt-6 grid gap-6 lg:grid-cols-2"><Card><h2 className="font-semibold text-slate-950">Crescimento de clínicas</h2><p className="mt-1 text-sm text-slate-600">Novos cadastros por dia, sem projeções.</p><div className="mt-5 flex h-40 items-end gap-1 overflow-hidden">{data.growth.map(point => <div className="flex min-w-1 flex-1 flex-col items-center justify-end gap-1" key={point.date} title={`${point.date}: ${point.newClinics} clínica(s)`}><div className="w-full rounded-t bg-brand-500" style={{ height: `${Math.max(4, point.newClinics / maxGrowth * 100)}%` }} /></div>)}</div></Card><Card><h2 className="font-semibold text-slate-950">Funil comercial</h2><p className="mt-1 text-sm text-slate-600">Leads recebidos no período selecionado.</p><div className="mt-4 grid gap-3">{[["Novos", funnel?.new], ["Contactados", funnel?.contacted], ["Qualificados", funnel?.qualified], ["Demonstração", funnel?.demoScheduled], ["Ganhos", funnel?.won]].map(([label, value]) => <div className="flex items-center justify-between rounded-control bg-slate-50 px-3 py-2 text-sm" key={String(label)}><span>{label}</span><strong>{value}</strong></div>)}</div></Card></section>
      <section className="mt-6 grid gap-6 lg:grid-cols-2"><Card><div className="flex items-center justify-between"><div><h2 className="font-semibold text-slate-950">Clínicas em configuração</h2><p className="mt-1 text-sm text-slate-600">Avance o setup sem expor dados sensíveis.</p></div><Link className="text-sm font-medium text-brand-700" href="/platform">Ver todas</Link></div><div className="mt-4 grid gap-2">{data.clinics.length ? data.clinics.map(clinic => <Link className="rounded-control border border-slate-200 p-3 hover:bg-slate-50" href={`/platform/clinics/${clinic.tenantId}`} key={clinic.tenantId}><div className="flex items-center justify-between gap-3 text-sm"><strong>{clinic.name}</strong><StatusBadge tone="info">{clinic.setupCompleted}/{clinic.setupTotal}</StatusBadge></div><p className="mt-1 text-xs text-slate-500">{clinic.clinicAdminName ?? "Administrador pendente"}</p></Link>) : <p className="text-sm text-slate-600">Nenhuma clínica em configuração.</p>}</div></Card><Card><h2 className="font-semibold text-slate-950">Saúde dos serviços</h2><div className="mt-4 grid gap-2">{data.health.map(item => <div className="flex items-center justify-between rounded-control border border-slate-200 p-3 text-sm" key={item.service}><span>{item.service}</span><StatusBadge tone={item.status === "Operacional" ? "success" : "warning"}>{item.status}</StatusBadge></div>)}</div></Card></section>
      <section className="mt-6 grid gap-6 lg:grid-cols-2"><Card><h2 className="font-semibold text-slate-950">Atenção necessária</h2><div className="mt-4 grid gap-2">{data.attention.map(item => item.actionUrl ? <Link className="rounded-control border border-slate-200 p-3 text-sm hover:bg-slate-50" href={item.actionUrl} key={item.title}><strong>{item.title}</strong><span className="mt-1 block text-slate-600">{item.description}</span></Link> : <div className="rounded-control border border-slate-200 p-3 text-sm" key={item.title}><strong>{item.title}</strong><span className="mt-1 block text-slate-600">{item.description}</span></div>)}</div></Card><Card><h2 className="font-semibold text-slate-950">Atividade recente</h2><div className="mt-4 grid gap-3">{data.recentActivity.length ? data.recentActivity.map(item => <div className="border-b border-slate-100 pb-3 text-sm last:border-0" key={`${item.occurredAt}-${item.title}`}><strong>{item.title}</strong><p className="text-slate-600">{item.description}</p><time className="text-xs text-slate-500">{new Date(item.occurredAt).toLocaleString("pt-BR")}</time></div>) : <p className="text-sm text-slate-600">Nenhuma atividade no período.</p>}</div></Card></section></>}
  </PageContainer>;
}

export default function DashboardPage() {
  const { user, authReady } = useAuth();
  if (!authReady || !user) return <ProtectedShell><PageContainer><Skeleton className="h-40" /></PageContainer></ProtectedShell>;
  return user.role === "PlatformAdmin" ? <ProtectedShell><PlatformDashboardPage /></ProtectedShell> : <ClinicDashboardPage />;
}
