"use client";

import Link from "next/link";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { zodResolver } from "@hookform/resolvers/zod";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/surfaces";
import { FormField, Input, Textarea } from "@/components/ui/form";
import { trackPublicEvent } from "@/lib/analytics/public-events";

const schema = z.object({ fullName: z.string().trim().min(2, "Informe seu nome completo."), companyOrClinicName: z.string().trim().min(2, "Informe o nome da clínica ou empresa."), email: z.string().email("Informe um e-mail válido."), phone: z.string().trim().min(8, "Informe um telefone válido."), description: z.string().max(2000, "Use no máximo 2.000 caracteres.").optional(), website: z.string().optional() });
type Form = z.infer<typeof schema>;

export default function DemonstracaoPage() {
  const [submitted, setSubmitted] = useState(false);
  const { register, handleSubmit, formState: { errors, isSubmitting }, setError } = useForm<Form>({ resolver: zodResolver(schema), defaultValues: { website: "" } });
  const submit = async (data: Form) => { trackPublicEvent("lead_started"); try { const params = new URLSearchParams(window.location.search); const attribution = { utmSource: params.get("utm_source")?.slice(0, 100) || undefined, utmMedium: params.get("utm_medium")?.slice(0, 100) || undefined, utmCampaign: params.get("utm_campaign")?.slice(0, 200) || undefined, utmContent: params.get("utm_content")?.slice(0, 200) || undefined, utmTerm: params.get("utm_term")?.slice(0, 200) || undefined }; const response = await fetch(`${process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8080"}/api/leads/demo-requests`, { method: "POST", headers: { "Content-Type": "application/json", Accept: "application/json" }, body: JSON.stringify({ ...data, ...attribution, landingPage: window.location.pathname, referrer: document.referrer ? document.referrer.slice(0, 1000) : undefined }) }); if (!response.ok) throw new Error("request_failed"); setSubmitted(true); trackPublicEvent("lead_submitted"); } catch { setError("root", { message: "Não foi possível enviar agora. Tente novamente em instantes." }); trackPublicEvent("lead_failed"); } };
  return <main className="min-h-screen bg-slate-50 px-5 py-10 text-slate-950"><div className="mx-auto max-w-3xl"><Link href="/" className="text-sm text-brand-700">← Voltar para a IA Recepção</Link><div className="mt-8"><p className="text-sm font-semibold uppercase tracking-[.18em] text-brand-600">Solicitar demonstração</p><h1 className="mt-3 text-4xl font-semibold tracking-tight">Vamos entender a rotina da sua clínica.</h1><p className="mt-4 max-w-2xl text-lg leading-8 text-slate-600">Preencha seus dados e nossa equipe entrará em contato para apresentar a IA Recepção e entender como ela pode se encaixar na sua operação.</p></div><Card className="mt-8 p-6 sm:p-8">{submitted ? <div role="status" className="py-8"><h2 className="text-2xl font-semibold">Recebemos seus dados.</h2><p className="mt-3 text-slate-600">Nossa equipe entrará em contato em breve. Obrigado pelo interesse na IA Recepção.</p><Link href="/" className="mt-6 inline-block text-brand-700">Voltar para a página inicial</Link></div> : <form className="grid gap-5" onSubmit={handleSubmit(submit)} noValidate><div className="grid gap-5 sm:grid-cols-2"><FormField error={errors.fullName?.message} htmlFor="fullName" label="Nome completo" required><Input id="fullName" autoComplete="name" {...register("fullName")} /></FormField><FormField error={errors.companyOrClinicName?.message} htmlFor="companyOrClinicName" label="Clínica ou empresa" required><Input id="companyOrClinicName" autoComplete="organization" {...register("companyOrClinicName")} /></FormField></div><div className="grid gap-5 sm:grid-cols-2"><FormField error={errors.email?.message} htmlFor="email" label="E-mail" required><Input id="email" type="email" autoComplete="email" {...register("email")} /></FormField><FormField error={errors.phone?.message} htmlFor="phone" label="Telefone" required><Input id="phone" type="tel" autoComplete="tel" {...register("phone")} /></FormField></div><FormField error={errors.description?.message} htmlFor="description" label="Conte um pouco sobre sua necessidade"><Textarea id="description" rows={5} {...register("description")} /></FormField><div className="absolute -left-[10000px]" aria-hidden="true"><label htmlFor="website">Website</label><input id="website" tabIndex={-1} autoComplete="off" {...register("website")} /></div>{errors.root?.message && <p role="alert" className="rounded-control border border-red-200 bg-red-50 p-3 text-sm text-red-900">{errors.root.message}</p>}<div><Button loading={isSubmitting} type="submit">{isSubmitting ? "Enviando..." : "Solicitar demonstração"}</Button><p className="mt-3 text-xs text-slate-500">Não envie dados de pacientes ou informações clínicas sensíveis neste formulário.</p></div></form>}</Card></div></main>;
}
